### ISSUE TITLE
[BUG][OpenSearch Dashboards] Mounted Certificates with wrong file permissions

### ISSUE THREAD

**Issue by doge95** [opensearch-project/helm-charts#115]
**Describe the bug**
I was testing self-signed certificates and found that mounted certificates were with wrong permissions and pod crashes due to this issue. 

**To Reproduce**
1. Create self-signed certificates and create secrets in Kubernetes. 
```
# k get secret -n test
NAME                                     TYPE                                  DATA   AGE
opensearch-ca                            Opaque                                1      3d18h
opensearch-certificate-key               Opaque                                1      3d18h
opensearch-certificate-pem               Opaque                                1      3d18h
```
2. Deploy OpenSearch Dashboards with values.yaml
```
replicaCount: 3
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
config:
  # Default OpenSearch Dashboards configuration from docker image of Dashboards
   opensearch_dashboards.yml:
    server:
      name: dashboards
      host: 0.0.0.0
     # Dashboards TLS Config (Ensure the cert files are present before enabling SSL
      ssl:
        enabled: true
        key: /usr/share/opensearch-dashboards/config/dashboards-key.pem
        certificate: /usr/share/opensearch-dashboards/config/dashboards-crt.pem
      
    logging.verbose: true
    
  # determines how dashboards will verify certificates (needs to be none for default opensearch certificates to work)
    opensearch:
      ssl:
        certificateAuthorities: /usr/share/opensearch-dashboards/config/dashboards-root-ca.pem
        # if utilizing custom CA certs for connection to opensearch, provide the CA here
secretMounts: 
  - name: opensearch-ca
    secretName: opensearch-ca
    path: /usr/share/opensearch-dashboards/config/dashboards-root-ca.pem
    subPath: dashboards-root-ca.pem
  - name: opensearch-certificate-pem
    secretName: opensearch-certificate-pem
    path: /usr/share/opensearch-dashboards/config/dashboards-crt.pem
    subPath: dashboards-crt.pem
  - name: opensearch-certificate-key
    secretName: opensearch-certificate-key
    path: /usr/share/opensearch-dashboards/config/dashboards-key.pem
    subPath: dashboards-key.pem
```
3. Exec into the container. Found that all mounted certificates with wrong file permissions. 
```
[opensearch-dashboards@osd-opensearch-dashboards-7d4d78d98b-2snh7 config]$ ls -lrt
total 16
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards  216 Jul  2 23:30 node.options
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards 1675 Jul  9 19:06 opensearch.example.org.key
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards 1151 Jul  9 19:06 opensearch.example.org.cert
-rw-r--r-- 1 root                  opensearch-dashboards  344 Nov  1 07:19 opensearch_dashboards.yml
drwxrwsrwt 2 root                  opensearch-dashboards   40 Nov  1 07:19 dashboards-root-ca.pem
drwxrwsrwt 2 root                  opensearch-dashboards   40 Nov  1 07:19 dashboards-crt.pem
drwxrwsrwt 2 root                  opensearch-dashboards   40 Nov  1 07:19 dashboards-key.pem
```
4. Pod crashes with error:
```
{"type":"log","@timestamp":"2021-11-01T07:25:08Z","tags":["fatal","root"],"pid":1,"message":"{ Error: EISDIR: illegal operation on a directory, read\n    at Object.readSync (fs.js:498:3)\n    at tryReadSync (fs.js:332:20)\n    at readFileSync (fs.js:369:19)\n    at readFile (/usr/share/opensearch-dashboards/src/core/server/http/ssl_config.js:181:31)\n    at new SslConfig (/usr/share/opensearch-dashboards/src/core/server/http/ssl_config.js:131:18)\n    at new HttpConfig (/usr/share/opensearch-dashboards/src/core/server/http/http_config.js:175:16)\n    at MapSubscriber.HttpService.config$.pipe [as project] (/usr/share/opensearch-dashboards/src/core/server/http/http_service.js:61:177)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18) errno: -21, syscall: 'read', code: 'EISDIR' }"}
{"type":"log","@timestamp":"2021-11-01T07:25:08Z","tags":["debug","server"],"pid":1,"message":"stopping server"}
{"type":"log","@timestamp":"2021-11-01T07:25:09Z","tags":["debug","legacy-service"],"pid":1,"message":"stopping legacy service"}
{"type":"log","@timestamp":"2021-11-01T07:25:09Z","tags":["debug","plugins-service"],"pid":1,"message":"Stopping plugins service"}
{"type":"log","@timestamp":"2021-11-01T07:25:09Z","tags":["debug","opensearch-service"],"pid":1,"message":"Stopping opensearch service"}

 FATAL  Error: EISDIR: illegal operation on a directory, read
```
**Expected behavior**
Mounted certificates with proper file permissions. 

**Chart Name**
OpenSearch Dashboards

**Host/Environment (please complete the following information):**
 - Helm Version: v3.7.0
 - Kubernetes Version: v1.22.1

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo any insight on this issue with certificates?
Thanks.

**Comment by DandyDeveloper** [comment]
@doge95 Just to verify, can you provide the `securityContext` from the container and whether this is `hostNetwork: true`? 

This should be in the manifest of the nodes.

**Comment by doge95** [comment]
> @doge95 Just to verify, can you provide the `securityContext` from the container and whether this is `hostNetwork: true`?
> 
> This should be in the manifest of the nodes.

Hi @DandyDeveloper,
Is this what you are looking for?
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    configchecksum: 908289744d3dd989932d4f9399b2d0d25e327a41af66a5aaf69867e1ad6407b
  creationTimestamp: "2021-11-03T10:49:16Z"
  finalizers:
  - kuryr.openstack.org/pod-finalizer
  generateName: test-dashboards-7687f5fc56-
  labels:
    app: dashboards
    pod-template-hash: 7687f5fc56
    release: test
  name: test-dashboards-7687f5fc56-kcb7c
  namespace: test
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: test-dashboards-7687f5fc56
    uid: 9f3410ed-d0d5-4d1c-89e8-f1a85a371fa5
  resourceVersion: "10742481"
  uid: cc2b8b46-3f14-4222-ab6a-a9bbdf957232
spec:
  containers:
  - env:
    - name: OPENSEARCH_HOSTS
      value: https://opensearch-cluster-master:9200
    - name: SERVER_HOST
      value: 0.0.0.0
    image: opensearchproject/opensearch-dashboards:1.0.0
    imagePullPolicy: IfNotPresent
    name: dashboards
    ports:
    - containerPort: 5601
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/opensearch-dashboards/config/dashboards-root-ca.pem
      name: opensearch-ca
      subPath: dashboards-root-ca.pem
    - mountPath: /usr/share/opensearch-dashboards/config/dashboards-crt.pem
      name: opensearch-certificate-client-pem
      subPath: dashboards-crt.pem
    - mountPath: /usr/share/opensearch-dashboards/config/dashboards-key.pem
      name: opensearch-certificate-client-key
      subPath: dashboards-key.pem
    - mountPath: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      name: config
      subPath: opensearch_dashboards.yml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wl662
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: xxxxxx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  serviceAccount: test-dashboards-dashboards
  serviceAccountName: test-dashboards-dashboards
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: opensearch-ca
    secret:
      defaultMode: 420
      secretName: opensearch-ca
  - name: opensearch-certificate-client-pem
    secret:
      defaultMode: 420
      secretName: opensearch-certificate-client-pem
  - name: opensearch-certificate-client-key
    secret:
      defaultMode: 420
      secretName: opensearch-certificate-client-key
  - configMap:
      defaultMode: 420
      name: test-dashboards-config
    name: config
  - name: kube-api-access-wl662
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by doge95** [comment]
@DandyDeveloper hey Dandy, any luck on this issue? :)

**Comment by DandyDeveloper** [comment]
@doge95 The problem is just a fundamental problem with Kubernetes when mounting.

The solution - `initContainer` that'll update permissions. I don't think we want this as default in the repo just yet (as this is the first report), but because of how mounts work, we'll need to do it in a frustrating way.

Unfortunately, I don't have any self-signed certs to hand and don't wanna make a root CA / script that out right now. But, can you try the following values?

test.yml
```sh
replicaCount: 3
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
config:
  # Default OpenSearch Dashboards configuration from docker image of Dashboards
   opensearch_dashboards.yml:
    server:
      name: dashboards
      host: 0.0.0.0
     # Dashboards TLS Config (Ensure the cert files are present before enabling SSL
      ssl:
        enabled: true
        key: /usr/share/opensearch-dashboards/certificates/dashboards-key.pem
        certificate: /usr/share/opensearch-dashboards/certificates/dashboards-crt.pem
      
    logging.verbose: true
    
  # determines how dashboards will verify certificates (needs to be none for default opensearch certificates to work)
    opensearch:
      ssl:
        certificateAuthorities: /usr/share/opensearch-dashboards/certificates/dashboards-root-ca.pem
        # if utilizing custom CA certs for connection to opensearch, provide the CA here
secretMounts: 
  - name: opensearch-ca
    secretName: opensearch-ca
    path: /usr/share/opensearch-dashboards/config/dashboards-root-ca.pem
    subPath: dashboards-root-ca.pem
  - name: opensearch-certificate-pem
    secretName: opensearch-certificate-pem
    path: /usr/share/opensearch-dashboards/config/dashboards-crt.pem
    subPath: dashboards-crt.pem
  - name: opensearch-certificate-key
    secretName: opensearch-certificate-key
    path: /usr/share/opensearch-dashboards/config/dashboards-key.pem
    subPath: dashboards-key.pem
extraInitContainers:
  - name: fix-permissions
    image: debian:buster-slim
    command: ["/bin/bash", "-c"]
    args:
    - cp -RL /usr/share/opensearch-dashboards/config/* /usr/share/opensearch-dashboards/certificates;
    - chown -R opensearch-dashboards:opensearch-dashboards /usr/share/opensearch-dashboards/certificates
    - find /usr/share/opensearch-dashboards/certificates -type d -exec chmod 700 {} \; ;
    - find /usr/share/opensearch-dashboards/certificates -type f -exec chmod 420 {} \; ;
    - ls -lrt /usr/share/opensearch-dashboards/config
    volumeMounts:
    - mountPath: /usr/share/opensearch-dashboards/certificates
      name: certificates-data
    - mountPath: /usr/share/opensearch-dashboards/config/dashboards-root-ca.pem
      name: opensearch-ca
      subPath: dashboards-root-ca.pem
    - mountPath: /usr/share/opensearch-dashboards/config/dashboards-crt.pem
      name: opensearch-certificate-client-pem
      subPath: dashboards-crt.pem
    - mountPath: /usr/share/opensearch-dashboards/config/dashboards-key.pem
      name: opensearch-certificate-client-key
      subPath: dashboards-key.pem
extraVolumes:
  - name: certificates-data
    emptyDir: {}
extraVolumeMounts:
  - name: certificates-data
    mountPath: /usr/share/opensearch-dashboards/certificates
```

If this fails, let me know the error and I'll have to try with my owned self-signed certs.

**Comment by doge95** [comment]
hi @DandyDeveloper, thanks for the workaround. I tried your settings in my local environment but still experienced the same issue.

When I exec into the container, the file/ directory permissions are shown as below.
```
[opensearch-dashboards@os-dashboards-86759b4bc8-vmgzm ~]$ ls -lrt   
total 1200
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards     831 Jul  2 23:30 package.json
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards    5284 Jul  2 23:30 README.txt
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards 1141870 Jul  2 23:30 NOTICE.txt
-rw-r--r-- 1 opensearch-dashboards opensearch-dashboards   11358 Jul  2 23:30 LICENSE.txt
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    4096 Jul  8 22:37 src
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards   24576 Jul  8 22:37 node_modules
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    4096 Jul  8 22:37 node
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    4096 Jul  8 22:37 bin
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    4096 Jul  8 22:37 plugins
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    6390 Jul  9 19:06 opensearch-dashboards-docker-entrypoint.sh
drwxrwsrwx 5 root                  opensearch-dashboards    4096 Dec  3 09:26 certificates
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    4096 Dec  3 09:26 config
drwxr-xr-x 1 opensearch-dashboards opensearch-dashboards    4096 Dec  3 09:26 data
[opensearch-dashboards@os-dashboards-86759b4bc8-vmgzm ~]$ cd certificates/
[opensearch-dashboards@os-dashboards-86759b4bc8-vmgzm certificates]$ ls -lrt
total 12
drwxr-sr-t 2 opensearch-dashboards opensearch-dashboards 4096 Dec  3 09:26 dashboards-crt.pem
drwxr-sr-t 2 opensearch-dashboards opensearch-dashboards 4096 Dec  3 09:26 dashboards-root-ca.pem
drwxr-sr-t 2 opensearch-dashboards opensearch-dashboards 4096 Dec  3 09:26 dashboards-key.pem
``` 
Looks like the directory and certificate file permissions are not correct.
```
drwxrwsrwx 5 root                  opensearch-dashboards    4096 Dec  3 09:26 certificates
```
```
drwxr-sr-t 2 opensearch-dashboards opensearch-dashboards 4096 Dec  3 09:26 dashboards-crt.pem
drwxr-sr-t 2 opensearch-dashboards opensearch-dashboards 4096 Dec  3 09:26 dashboards-root-ca.pem
drwxr-sr-t 2 opensearch-dashboards opensearch-dashboards 4096 Dec  3 09:26 dashboards-key.pem
```

**Comment by doge95** [comment]
hi @DandyDeveloper, is there any recommended way to use certificates (other than self-signed certs) for opensearch-dashboards to enable security?

**Comment by thanatas** [comment]
Any luck on this issue, I am stuck! Thanks.

**Comment by NybbleHub** [comment]
Hello !

On my side I solved permissions issues with the following configuration:

1. Create a secret containing ca cert, tls cert, tls key:
```
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-tls-certificates
  namespace: opensearch
type: Opaque
data:
  tls.crt: $base64_content
  tls.key: $base64_content
  ca.crt: $base64_content
```
2. Mount your secret in separated folder and specify mode with the following configuration in `values.yml`: 
```
...
secretMounts:
  - name: opensearch-http-certificates
    secretName: opensearch-tls-certificates
    path: /usr/share/opensearch-dashboards/certs/
    defaultMode: 0644
...
```
3. Add the following configuration in `opensearch_dashboards.yml:` section in `values.yml`: 
```
...
    opensearch.ssl.certificate: /usr/share/opensearch-dashboards/certs/tls.crt
    opensearch.ssl.key: /usr/share/opensearch-dashboards/certs/tls.key
    opensearch.ssl.certificateAuthorities: [ "/usr/share/opensearch-dashboards/certs/ca.crt" ]
...
```

With that you should not need an Extra Init container to modifiy the permissions.

**Comment by peterzhuamazon** [comment]
Close this for now as it seems to be resolved by community.
Please feel free to re-open if you still have questions.

Thanks.

**Comment by SmartGuyy** [comment]
Hi, i'm reopening this issue as all suggestions to solve this issue did not succeed for me. 

I used the scripts : https://opensearch.org/docs/latest/security-plugin/configuration/generate-certificates/#sample-script to generate my certs and import them in a secret.

I have a config that is working without certs, but for security reasons, i need it so it can go to production.

Here is what i tried : 


`  ## SOLUTION 1 : mount as a secret with defaultMode 0644
  ## RESULT : java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/share/opensearch/certs/esnode.pem" "read")

  secretMounts:
  - name: certs
    secretName: opensearch-certs
    path: /usr/share/opensearch/certs
    defaultMode: 0644

  ## SOLUTION 2 : mount an empty volume only with "certs" folder, change permissions and then import secrets
  ## RESULT : initcontainer isn't able to change permissions, as files are in read only mode
  ## tried to "chattr -i -f" but doesn't work as there are symlinks
  ## i even tried to put initContainer as root and perform actions within the container to give permissions but nothing worked

  # extraVolumes:
  # - name: certificates-data
  #   emptyDir: {}
  # extraVolumeMounts:
  # - name: certificates-data
  #   mountPath: /usr/share/opensearch/certs
  # extraInitContainers:
  # - name: fix-permissions
  #   image: debian:buster-slim
  #   command: ["/bin/bash", "-c"]
  #   securityContext:
  #     privileged: true
  #     runAsNonRoot: false
  #     runAsUser: 0
  #   args:
  #   # NOTE : chattr -i doesn't work as their are symlinks
  #   - chattr -i -f /usr/share/opensearch/certs/esnode-key.pem;
  #   - chattr -i -f /usr/share/opensearch/certs/esnode.pem;
  #   - chattr -i -f /usr/share/opensearch/certs/root-ca.pem;
  #   - chown -R 1000:1000 /usr/share/opensearch/certs;
  #   - find /usr/share/opensearch/certs -type d -exec chmod 700 {} \; ;
  #   - find /usr/share/opensearch/certs -type f -exec chmod 420 {} \; ;
  #   - find /usr/share/opensearch/config -type d -exec chmod 700 {} \; ;
  #   - find /usr/share/opensearch/config -type f -exec chmod 420 {} \; ;
  #   - ls -lrt /usr/share/opensearch/certs

  #   volumeMounts:
  #   - mountPath: /usr/share/opensearch/certs
  #     name: certificates-data
  #     readOnly: false

  ## SOLUTION 3 : mount secret as a volume with defaultMode 0644
  ## same results than solution 1 even if i mount it on initContainer and try to give permissions
  
  # extraVolumes:
  # - name: certs
  #   secret: 
  #     defaultMode: 0644
  #     secretName: opensearch-certs
  # extraVolumeMounts:
  # - mountPath: /usr/share/opensearch/certs
  #   name: certs
  # - name: config
  #   secretName: opensearch-config
  #   path: /usr/share/opensearch/config`

Of course with all those solution, i tried to add few settings like "readOnly : false", run as root, etc... 

Note that i have this issue for Opensearch chart and not for Opensearch-Dashboards but it is basically the same issue.

**Comment by DandyDeveloper** [comment]
@SmartGuyy @pettax For my sake, can you provide the certificates you generated to save me some time? I'll experiment and try to provide a solid values for this.

**Comment by pettax** [comment]
> @SmartGuyy @pettax For my sake, can you provide the certificates you generated to save me some time? I'll experiment and try to provide a solid values for this.

The certs I am trying to use for this attempt are generated by [cert-manager](https://cert-manager.io/docs/) and the YAML-files used for this are basically a carbon copy of what is in this [blog](https://eliatra.com/blog/opensearch-with-cert-manager-part-2-self-signed-ca/). The problem does not seem to be the certificates though but the ownership and/or permissions set on the files when mounting them.

Attempting with this init container to fix owner/permissions:
```
extraInitContainers:
  - name: fix-permissions
    image: alpine:3.6
    command: ["sh", "-c", "cp /root-key/* /usr/share/opensearch/config/certs/ && chown -R 1000:1000 /usr/share/opensearch/config/certs/ && chmod 644 /usr/share/opensearch/config/certs/*"]
    securityContext:
      privileged: true
      runAsNonRoot: false
      runAsUser: 0
    volumeMounts:
    - mountPath: /usr/share/opensearch/config/certs
      name: key-volume
    - mountPath: /root-key
      name: root-owned-key-volume
```

I get the following error message from opensearch:
`Unable to read /usr/share/opensearch/config/certs/key.crt (/usr/share/opensearch/config/certs/key.crt). Please make sure this files exists and is readable`

The container crashes as a result so it is a bit hard to inspect the resulting file system.

**Comment by pettax** [comment]
With the help of a good set of eyes, I found that I have configured the key file to be called `key.crt` but the file was actually called `tls.key`. With that corrected and with the init container above it actually works now!

**Comment by SmartGuyy** [comment]
@pettax at the end i did use the same tutorial for cert-manager than you and had to struggle a lot to find the logic behind with all resources that i found on Google. Now i think it seems to load correctly. Once i will have everything set up, i will post a sample of working configuration for people that will come behind us with the same issue... i nearly worked on this problem for about 1-2 weeks, such a pain !

Right now i'm trying to configure admin certs to apply security admin conf (one more point that is not really covered by tutorials/resources...)

**Comment by SmartGuyy** [comment]
As promised, here is a sample of configuration that is working for us (you must already have certificate issuer for letsencrypt-prod with cert-manager) : 

certificates.yaml
`apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-for-opensearch
  namespace: opensearch
spec:
  secretName: tls-for-opensearch
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: yourdomain.com
  dnsNames:
  - yourdomain.com
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-for-dashboards
  namespace: opensearch
spec:
  secretName: tls-for-dashboards
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: yourdomain.com
  dnsNames:
  - yourdomain.com
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-dn
  namespace: opensearch
spec:
  secretName: admin-dn
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: admin.yourdomain.com
  dnsNames:
  - admin.yourdomain.com
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth`
    
dashbords-conf.yaml :
`apiVersion: v1
kind: Secret
metadata:
  name: opensearch-dashboards-config
type: Opaque
stringData:
  opensearch_dashboards.yml: |-
    server.host: '0.0.0.0'
    #logging.verbose: true
    opensearch.ssl.verificationMode: certificate
    opensearch.requestHeadersWhitelist: [authorization, securitytenant]
    server.ssl.enabled: true
    server.ssl.key: /usr/share/opensearch-dashboards/certs/tls.key
    server.ssl.certificate: /usr/share/opensearch-dashboards/certs/tls.crt

    opensearch.ssl.certificateAuthorities: ["/usr/share/opensearch-dashboards/certs/ca/ca-root.pem"]
    opensearch.username: "yourusername"
    opensearch.password: "yourpassword"
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred: [Global, Private]
    opensearch_security.readonly_mode.roles: [kibana_read_only]
    opensearch_security.multitenancy.tenants.enable_global: true
    opensearch_security.multitenancy.tenants.enable_private: true
`
ingress.yaml : 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: opensearch-server-ingress
 namespace: opensearch
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  spec:
 tls:
   - hosts:
       - yourdomain.com
     secretName: tls-for-opensearch
 rules:
   - host: yourdomain.com
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: opensearch-cluster-master
               port:
                 number: 9200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-dashboard-ingress
  namespace: opensearch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
    - hosts:
        - yourdomain.com
      secretName: tls-for-dashboards
  rules:
    - host: yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-opensearch-dashboards
                port:
                  number: 5601`

and the values.yaml (the part with volumes and with extraInitContainers should be in both Opensearch and Opensearch-Dashboards) : 
` 
opensearch: 
 extraVolumes:
    - name: ca-cert
      emptyDir: {}

  extraVolumeMounts:
    - name: ca-cert
      mountPath: /usr/share/opensearch/config/certs/ca
      readOnly: true

  extraInitContainers: 
    - name: init-script-downloader
      image: appropriate/curl
      args:
        - "-k"
        - "-o"
        - "/tmp/ca-root.pem" # we are saving downloaded file as init.sql in /tmp/data directory
        - "https://letsencrypt.org/certs/isrgrootx1.pem" # PROD root cert
        # - https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem # STAGING root cert
      volumeMounts:
      - name: ca-cert # mount the volume where downloaded file will be saved
        mountPath: /tmp
  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      action.auto_create_index: true

      # Bind to all interfaces because we don't know what IP address Docker will assign to us.
      network.host: 0.0.0.0
      # WARNING: revise all the lines below before you go into production
      plugins:
        security:
          nodes_dn:
            - 'CN=yourdomain.com
          ssl:
            transport:
              pemcert_filepath: certs/tls.crt
              pemkey_filepath: certs/tls.key
              pemtrustedcas_filepath: certs/tls.crt
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: certs/tls.crt
              pemkey_filepath: certs/tls.key
              pemtrustedcas_filepath: certs/tls.crt
          allow_unsafe_democertificates: false
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
            - 'CN=admin.yourdomain.com'
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]
  # Extra environment variables to append to this nodeGroup
  # This will be appended to the current 'env:' key. You can use any of the kubernetes env
  # syntax here
  extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"

  # A list of secrets and their paths to mount inside the pod
  # This is useful for mounting certificates for security and for mounting
  # the X-Pack license
  secretMounts: 
    - name: opensearch-certs
      secretName: tls-for-opensearch
      path: /usr/share/opensearch/config/certs
    - name: admin-dn
      secretName: admin-dn
      path: /usr/share/opensearch/config/certs/admin-dn

opensearch-dashboards:

  secretMounts: 
    - name: opensearch-certs
      secretName: tls-for-dashboards
      path: /usr/share/opensearch-dashboards/certs
    - name: opensearch-dashboards-config
      secretName: opensearch-dashboards-config
      path: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      subPath: opensearch_dashboards.yml

  extraEnvs:
    - name : NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"

  extraVolumes:
    - name: ca-cert
      emptyDir: {}

  extraVolumeMounts:
    - name: ca-cert
      mountPath: /usr/share/opensearch-dashboards/certs/ca
      readOnly: true

  extraInitContainers: 
    - name: init-script-downloader
      image: appropriate/curl
      args:
        - "-k"
        - "-o"
        - "/tmp/ca-root.pem" # we are saving downloaded file as init.sql in /tmp/data directory
        - "https://letsencrypt.org/certs/isrgrootx1.pem" # PROD root cert
        #- https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem # STAGING root cert
      volumeMounts:
      - name: ca-cert # mount the volume where downloaded file will be saved
        mountPath: /tmp `

**Comment by jimsnab** [comment]
I got this to work but had to struggle with comments above. Maybe this additional detail will help someone.

Here is the issue: the `secretMounts` sets the owner to root, and files are mounted read-only. It is not possible `chown` to opensearch. The cert is accessible, but the Java security manager disallows opensearch's access to the cert and throws access denied. So it is a requirement to copy the certs and `chown`, and remove `secretMounts` from the `values.yaml`.

I also found that `defaultMode` that is all over this thread is a no-op. The permissions are already 420 (e.g., 0644).

So I added this to my `values.yaml`:

```
extraVolumes:
  # a place to store copied certs, filled by init container bash script, then mounted into opensearch container
  - name: certificates-data
    emptyDir: {}

  # volume from the tls secret, mounted into the init container only via its volumeMounts
  - name: opensearch-certs
    secret:
      defaultMode: 420
      secretName: "my_tls_secret_name"
```

My init container was already there, to set vm.max_map_count to 262144 to resolve some other problem. So I extended that bash script. Here's trimmed version for this bug:

```
extraInitContainers:
  - name: fixcerts
    image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
    imagePullPolicy: "IfNotPresent"
    command:
      - /bin/bash
      - -ec
      - |
        cp /certs/* /certs-copy
        chown -R 1000:1000 /certs-copy

    # this securityContext is probably only needed for fixing vm.max_map_count, but including it here just in case
    securityContext:
      runAsUser: 0
      privileged: true

    volumeMounts:
      # tls cert source, from the secret volume
      - mountPath: /certs
        name: opensearch-certs
      # the output volume - the mount path can be anything but needs to match bash script above
      - mountPath: /certs-copy
        name: certificates-data
```

Finally, once `certificates-data` volume is prepared, it needs to be mounted into the opensearch container.

```
# mount owner-fixed certs into opensearch container, must be inside config dir
extraVolumeMounts:
  - name: certificates-data
    mountPath: /usr/share/opensearch/config/certs
```

And now the config:

```
config:
  opensearch.yml: |
. . .
    plugins:
      security:
        ssl:
          . . .
          http:
            enabled: true

            # file names are defined in the kubesecret
            pemcert_filepath: /usr/share/opensearch/config/certs/tls.crt                                                                                                                
            pemkey_filepath: /usr/share/opensearch/config/certs/tls.key                                                                                                                 
            pemtrustedcas_filepath: /usr/share/opensearch/config/certs/root-ca-cert.pem  
. . .
```

Tip: turn `http.enabled` to false, then shell into the opensearch container, to browse around and verify files are right.

Tip: add `sleep 60` or something like that to the bash script, and then you have some time to shell into the init container to verify the init script.
