### ISSUE TITLE
[Enhancement][opensearch] Document how to use the security config.yml with Helm charts

### ISSUE THREAD

**Issue by trondhindenes** [opensearch-project/helm-charts#125]
I'm just getting aquainted wiht Opensearch and its Helm charts. The default installation works well, but I'm specifically looking into security and for instance trying to hook up an OpenID auth provider. The Opensearch documentation describes configuring these things using the `config.yml` file in the security-plugin folder. 

Problem: it's not clear from the documentation how to add settings to this file using Helm. In the values file there is a `config` section which contains settings for the `opensearch.yml` file and I see some security-related settings in there. It's not clear to me what the relationship is between security settings in opensearch.yml and the config.yml in the security plugin dir. 

The values.yml file also mentions that it can be used to add files to `<opensearchHome>/config` but makes no mention of configuring files in other dirs.

Another example thing I thought I could see if was possible is to set the `anonymous_auth_enabled: true` using Helm, but I have to admit it's not easy.

I wish there was better documentation for how to affect the security config of opensearch when using Helm.

**Comment by trondhindenes** [comment]
Looking closer at the values.yml file I'm seeing there's a  `securityConfig.config.data` and from the description it looks like there might be a way to configure the `config.yml`. However it looks like those are "basic" string values so it basically expects yaml-in-yaml which is pretty terrible from a user perspective. It's also unclear if the default `config.yml` values will get overwritten if the `securityConfig.config.data.config.yml` value is written.

**Comment by sevenval-admins** [comment]
Hi, I am also trying to configure the security plugin (I want to bind my opensearch to LDAP, so I have to write my own config.yml) and I think that all that has with security plugin to do can be configured with the parameters starting by this line https://github.com/opensearch-project/helm-charts/blob/773a413af09e8d2141c9359838b6cd5d76a095a4/charts/opensearch/values.yaml#L288 until line. 
I still did not try it but I think it will work, I will let you know :)

**Comment by NybbleHub** [comment]
Hi !

Here is how to be able to use custom Security Config and in particular for LDAP or OpenID provider, using Kubernetes Secret.

1. Create a secret containing your `config.yaml` content:
```
apiVersion: v1
kind: Secret
metadata:
  name: security-config-secret
  namespace: opensearch
type: Opaque
data:
  config.yaml: $base64_content
```
2. Use your newly created secret in `values.yml` file:
```
...
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
  actionGroupsSecret: action-groups-config-secret
  configSecret: security-config-secret
  internalUsersSecret: internal-users-config-secret
  rolesSecret: roles-config-secret
  rolesMappingSecret: roles-mapping-config-secret
  tenantsSecret: tenants-config-secret
...
```
3. That's it, your config should be applied at start. 

I hope this can help.
