### ISSUE TITLE
[BUG][opensearch] Added default value to securityConfigSecret

### ISSUE THREAD

**Issue by dotdc** [opensearch-project/helm-charts#146]
**Describe the bug**

Hi, I've initially been unable to load a custom `internal_users.yml` to my kubernetes helm chart deployment using both presented method in the values file (issue refer to the `elasticsearch.securityConfig.config.data.internal_users.yml` method).

To make it work, you need to add a default value to securityConfigSecret, here's the PR : https://github.com/opensearch-project/helm-charts/pull/142

This is a copy of the Opendistro issue : https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/702 (references and links below remain the same)

**To Reproduce**
1. Build opendistro helm chart (https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/)
2. Deploy with custom values (see `custom.values.yaml` below)
3. Check users on Kibana or in `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml` on the master pod

**Expected behavior**

This should load the custom `internal_users.yml` set in `custom.values.yaml `

**Configuration (please complete the following information):**
 - ODFE/Kibana version : 1.13.1
 - Distribution : Helm Chart
 - Kubernetes v1.18.16
 - Host Machine : Flatcar Container Linux by Kinvolk 2765.2.1 

**Aditionnal question**

In the default `internal_users.yml` there is several users other than `admin`:
- kibanaserver
- kibanaro
- logstash
- readall
- snapshotrestore

Are they used in any way or just here as an example?

**Relevant information**

custom.values.yaml :
```
---
elasticsearch:
  securityConfig:
    config:
      data:
        # config.yml: |-
        # roles.yml: |-
        # rolesMapping.yml: |-
        # tenants.yml: |-
        internal_users.yml: |-
          _meta:
            type: "internalusers"
            config_version: 2
          
          fluentbit:
            hash: "$2y$12$4uM.APaTAjDXKGGjmyCZYexXFFXUnZ4sXSv2nNrF0bmCJgY/cXmKW"
            reserved: false
            hidden: false
          
          admin:
            hash: "$2y$12$BrMTXYvq04gV3vMxAON7I.4/cXsxsf.nXqIur.gLGYlpydze3kRzq"
            reserved: true
            backend_roles:
            - "admin"
```
