### ISSUE TITLE
[BUG][opensearch] Demo certificates found but allow_unsafe_democertificates is false.

### ISSUE THREAD

**Issue by NybbleHub** [opensearch-project/helm-charts#154]
**Describe the bug**
Helm install is failling when I'm using my own certificates and I set `allow_unsafe_democertificates` to `false`. 

**To Reproduce**
1. Create the secrets containing the certificates with CertManager.
2. Use `secretMounts` in value.yml file to mount the secrets created with CertManager:
```
...
secretMounts:
  - name: opensearch-http-certificate
    secretName: opensearch-tls-certificate
    path: /usr/share/opensearch/config/certs/http
    defaultMode: 0644
  - name: opensearch-transport-certificate
    secretName: opensearch-tls-certificate
    path: /usr/share/opensearch/config/certs/transport
    defaultMode: 0644
  - name: opensearch-admin-certificate
    secretName: opensearch-admin-certificate
    path: /usr/share/opensearch/config/certs/admin
    defaultMode: 0644
...
```
3. Use mounted certificates in SSL configuration, disable use of Demo certificates and enable initialization of security index:
```
...
    plugins:
      security:
        ssl:
          transport:
            pemcert_filepath: certs/transport/tls.crt
            pemkey_filepath: certs/transport/tls.key
            pemtrustedcas_filepath: certs/transport/ca.crt
            enforce_hostname_verification: false
          http:
            enabled: true
            pemcert_filepath: certs/http/tls.crt
            pemkey_filepath: certs/http/tls.key
            pemtrustedcas_filepath: certs/http/ca.crt
        allow_unsafe_democertificates: false
        allow_default_init_securityindex: true
...
```
4. Container is starting but fails after some seconds with the following error:
```
...
[2021-12-01T11:02:20,968][ERROR][o.o.s.OpenSearchSecurityPlugin] [freddy-master-0] Demo certificates found but plugins.security.allow_unsafe_democertificates is set to false.
[2021-12-01T11:02:20,971][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [freddy-master-0] uncaught exception in thread [main]
...
Caused by: java.lang.RuntimeException: Demo certificates found [d14aefe70a592d7a29e14f3ff89c3d0070c99e87d21776aa07d333ee877e758f, 54a70016e0837a2b0c5658d1032d7ca32e432c62c55f01a2bf5adcb69a0a7ba9, bdc141ab2272c779d0f242b79063152c49e1b06a2af05e0fd90d505f2b44d5f5, 3e839e2b059036a99ee4f742814995f2fb0ced7e9d68a47851f43a3c630b5324, 9b13661c073d864c28ad7b13eda67dcb6cbc2f04d116adc7c817c20b4c7ed361]
...
```

**Expected behavior**
Ignore the Demo certificates if `secretMounts` is used or/and if  `allow_unsafe_democertificates` is set to `false`. 

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version: 3.6.3
 - Kubernetes Version: 1.20.9
 - Opensearch Version: 1.1.0
 - Opensearch Helm Chart Version : 1.4.3

**Comment by NybbleHub** [comment]
Apparently the "install_demo_configuration.sh" script is launched by default:

```
...
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-1.1.0
Detected OpenSearch Security Version: 1.1.0.0
...
```

Is there a way do disable the `install_demo_configuration.sh` script and use the `securityadmin.sh` script ?

**Comment by smlx** [comment]
This bug is actually in the upstream `opensearch` docker image. A workaround is to build a custom image based on upstream which removes those certificates. Something like this:
```
FROM opensearchproject/opensearch:1.0.0
RUN rm /usr/share/opensearch/config/*.pem
```

**Comment by NybbleHub** [comment]
I tried to remove the certificates with an extraInitContainer :

```
...
extraInitContainers:
  - name: remove-demo-certificates
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args: 
    - rm -rf /usr/share/opensearch/config/*.pem
...
```

But it's not working because Demo certificates are generated directly by `install_demo_configuration.sh`, they are hardcoded in the script.

I will try to find why and from which place this script is automatically launched.

**Comment by NybbleHub** [comment]
I found a workaround for this issue.

The `install_demo_configuration.sh` is runned at start via the `opensearch-docker-entrypoint.sh` script if `DISABLE_INSTALL_DEMO_CONFIG` is not `true`.

`DISABLE_INSTALL_DEMO_CONFIG` value is set in Dockerfile with `ARG DISABLE_INSTALL_DEMO_CONFIG=true` and is not kept as environment variable at start.

So the solution is to simply set an extraEnv : 
```
...
extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
...
```

With the following values in `opensearch.yml` :
```
  opensearch.yml: |
    plugins:
      security:
        allow_unsafe_democertificates: false
        allow_default_init_securityindex: true
...
```

With this config my master, data and client nodes are able to start and security plugin is able to initialized with value provided in `securityConfig`
