### ISSUE TITLE
[BUG][opensearch-dashboards] configMap does not renderd correctly

### ISSUE THREAD

**Issue by StefanSa** [opensearch-project/helm-charts#156]
**Describe the bug**
configMap does not renderd correctly

**To Reproduce**
with this values.yaml the configMap is not rendered correctly.

-snip-
```
config:
  opensearch_dashboards.yml: |
    opensearch.hosts: ["https://opensearch-cluster-master:9200"]
    opensearch.ssl.verificationMode: none
    opensearch.username: "kibanaserver"
    opensearch.password: "kibanaserver"
    opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
    server.ssl.enabled: true
    server.ssl.certificate: certs/tls.crt
    server.ssl.key: certs/tls.key
    opensearch.ssl.certificateAuthorities: certs/ca.crt
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]
    opensearch_security.cookie.secure: true
envFrom: []
```
-snap-

in the generated configMap there is one "Pipe Symbol" too much.
Result ConfigMap:
```
data:
  opensearch_dashboards.yml: |
    |
      opensearch.hosts: ["https://opensearch-cluster-master:9200"]
      opensearch.ssl.verificationMode: none
      opensearch.username: "kibanaserver"
      opensearch.password: "kibanaserver"
      opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
      server.ssl.enabled: true
      server.ssl.certificate: certs/tls.crt
      server.ssl.key: certs/tls.key
      opensearch.ssl.certificateAuthorities: certs/ca.crt
      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      opensearch_security.cookie.secure: true
#  key: string
```
The same works with the opensearch chart without problem.
What i have seen, is that opensearch and opensearch-dashboards have different configmap.yaml template files.

**Expected behavior**
correctly generated configMap.

**Chart Name**
opensearch-dashboards

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: [e.g. 3.x.x]
 - rancher: [e.g. 2.6.2.x]

**Comment by peterzhuamazon** [comment]
Hi @StefanSa great find.
Would you consider opening a PR for this?
Thanks.

**Comment by malcolm061990** [comment]
Hi guys.
I deployed opensearch-dashboards-1.2.0 helm chart in EKS. It successfully connects to AWS Managed OpenSearch.
Here is a piece of yaml file (all other values are default):
```yaml
opensearchHosts: ""

image:
  repository: "opensearchproject/opensearch-dashboards"
  tag: "1.1.0"

config:
    opensearch_dashboards.yml:
      server.host: '0.0.0.0'
      opensearch.hosts: ['https://123456.es.amazonaws.com:443']
      # opensearch_dashboards.index: ".username"
      # opensearch.ssl.verificationMode: none # if not using HTTPS

      opensearch_security.auth.type: basicauth
      opensearch_security.auth.anonymous_auth_enabled: false
      opensearch_security.cookie.secure: false # set to true when using HTTPS
      opensearch_security.cookie.ttl: 3600000
      opensearch_security.session.ttl: 3600000
      opensearch_security.session.keepalive: false
      opensearch_security.multitenancy.enabled: false
      opensearch_security.readonly_mode.roles: ['kibana_read_only']
      opensearch_security.auth.unauthenticated_routes: []
      opensearch_security.basicauth.login.title: 'Please log in using your user name and password'

      opensearch.username: '12345'
      opensearch.password: '123456'
      opensearch.requestHeadersWhitelist: [authorization, securitytenant,security_tenant]
```
