### ISSUE TITLE
[Helm] If cluster name is set anything apart from "opesearch-cluster", getting an error OpenSearch Security not initialised.

### ISSUE THREAD

**Issue by jasodeep** [opensearch-project/helm-charts#16]
**Describe the bug**
I tried deploying OpenSearch using the helm chart, it’s working fine when the cluster name is set to default opesearch-cluster, but when it’s set to something custom, it’s throwing error -
`OpenSearch Security not initialised`

**Values which resulting error -**
```
clusterName: "foobar"
nodeGroup: "master"
masterService: "foobar-master"
config:
  opensearch.yml:
    cluster.name: foobar-cluster
```

**Working Values**
```
clusterName: "opensearch-cluster"
nodeGroup: "master"
masterService: "opensearch-cluster-master"
config:
  opensearch.yml:
    cluster.name: opensearch-cluster
```
