### ISSUE TITLE
[BUG][opensearch/opensearch] securityadmin.sh is failing to update admin password

### ISSUE THREAD

**Issue by ognjen-it** [opensearch-project/helm-charts#161]
**Describe the bug**
Hi guys, I'm trying to deploy the OpenSearch cluster with no default password (password should be ognjen).

**To Reproduce**
1. Deploy OpenSearch cluster: `helm install opensearch-search opensearch/opensearch`
2. Ssh to pod and generate hashed password: `helm install opensearch-search opensearch/opensearch`
    - output example: $2y$12$kJXD1/8shSLN.ofPO2TaEeYorVdofZg3dn2NEs4S/D6p3FGwyhI/a
3. Deploy OpenSearch cluster: `helm install opensearch-search opensearch/opensearch -f opendistro-search.yaml`
 - opendistro-search.yaml:

```
clusterName: opensearch-search
masterService: opensearch-search-master
resources:
  requests:
    cpu: 100m 
securityConfig:
  config:
    data:
      internal_users.yml: |-
        # This is the internal user database
        # The hash value is a bcrypt hash and can be generated with plugin/tools/hash.sh
        _meta:
          type: "internalusers"
          config_version: 2
        # Define your internal users here
        ## Demo users
        admin:
          hash: "$2y$12$kJXD1/8shSLN.ofPO2TaEeYorVdofZg3dn2NEs4S/D6p3FGwyhI/a"
          reserved: true
          backend_roles:
          - "admin"
          description: "Demo admin user"
        kibanaserver:
          hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
          reserved: true
          description: "Demo OpenSearch Dashboards user"
        kibanaro:
          hash: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
          reserved: false
          backend_roles:
          - "kibanauser"
          - "readall"
          attributes:
            attribute1: "value1"
            attribute2: "value2"
            attribute3: "value3"
          description: "Demo OpenSearch Dashboards read only user"
        logstash:
          hash: "$2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2"
          reserved: false
          backend_roles:
          - "logstash"
          description: "Demo logstash user"
        readall:
          hash: "$2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2"
          reserved: false
          backend_roles:
          - "readall"
          description: "Demo readall user"
        snapshotrestore:
          hash: "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W"
          reserved: false
          backend_roles:
          - "snapshotrestore"
          description: "Demo snapshotrestore user"
```

2. port-forward service: kubectl port-forward svc/opensearch-search-master 9200:9200
3. try to get information: curl -k --user admin:ognjen -XGET -H 'Content-Type: application/json' https://localhost:9200/
    - output: OpenSearch Security not initialized.
4. Try run securityadmin.sh script:

```
/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh \
 -cd /usr/share/opensearch/plugins/opensearch-security/securityconfig/ \
 -icl -nhnv -cacert /usr/share/opensearch/config/root-ca.pem  \
 -cert /usr/share/opensearch/config/kirk.pem  \
 -key /usr/share/opensearch/config/kirk-key.pem \
 -h localhost
```

- output:

```
Security Admin v7
Will connect to localhost:9300 ... done
Connected as CN=kirk,OU=client,O=client,L=test,C=de
OpenSearch Version: 1.2.0
OpenSearch Security Version: 1.2.0.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: opensearch-search
Clusterstate: GREEN
Number of nodes: 3
Number of data nodes: 3
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /usr/share/opensearch/plugins/opensearch-security/securityconfig/
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml (No such file or directory)
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml (No such file or directory)
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml (No such file or directory)
Will update '_doc/internalusers' with /usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml (No such file or directory)
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml (No such file or directory)
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/nodes_dn.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/nodes_dn.yml (No such file or directory)
ERR: Seems /usr/share/opensearch/plugins/opensearch-security/securityconfig/whitelist.yml is not in OpenSearch Security 7 format: java.io.FileNotFoundException: /usr/share/opensearch/plugins/opensearch-security/securityconfig/whitelist.yml (No such file or directory)
ERR: cannot upload configuration, see errors above
```

**Expected behavior**
Expect to change the default password from **admin** to **ognjen**

**Chart Name**
1.5.0

**Screenshots**
![image](https://user-images.githubusercontent.com/44586606/144868702-d0856c92-aa01-4cfb-9022-c2a89757cd33.png)

**Host/Environment (please complete the following information):**
 - Helm Version: v3.5.1
 - Kubernetes Version: v1.18.8

**Additional context**
It could be nice if we would be able in the future to set the password in Kubernetes Object: Secret
