### ISSUE TITLE
[BUG][opensearch] Authentication failed for opensearch dashboards with updated kibanaserver password

### ISSUE THREAD

**Issue by doge95** [opensearch-project/helm-charts#186]
**Describe the bug**
I create a separated secret containing my ```internal_users.yml``` (changed the default password for ```kibanaserver``` user) configuration and then specify the secret name in ```securityConfig.internalUsersSecret```.

I update```opensearch.password``` in ```opensearch_dashboards.yml``` 

However, the opensearch dashboards pod **fails to authenticate** to the opensearch master pod with ```kibanaserver``` user and the new password. 

Opensearch master pod logs:
```
[2021-12-23T08:42:08,201][INFO ][o.o.s.c.ConfigurationRepository] [opensearch-cluster-master-0] Node 'opensearch-cluster-master-0' initialized
[2021-12-23T08:42:09,426][WARN ][o.o.s.a.BackendRegistry  ] [opensearch-cluster-master-0] Authentication finally failed for kibanaserver from 11.127.4.164:45618
```

When I curl the opensearch endpoints with the new credentials, it works.
```
[opensearch-dashboards@opensearch-dashboards-8c7b678b5-nkzcm ~]$ curl -k https://kibanaserver:k$VK57-8@opensearch-cluster-master:9200
{
  "name" : "opensearch-cluster-master-0",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "DpYurGvrSu68uN4Q36b6Vg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.1",
    "build_type" : "tar",
    "build_hash" : "e3a44fa71b290fb265a94ef4297f044b9a63a762",
    "build_date" : "2021-12-11T04:22:52.398139Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**To Reproduce**
1. Deploy the opensearch chart; exec into the pod and generate the hashed password: 
```plugins/opensearch-security/tools/hash.sh -p k$VK57-8```
2. Replace the new hash value in ```internal_users.yml``` for ```kibanaserver```
3. Create a secret using the ```internal_users.yml``` file
```k create secret generic opensearch-internal-users -n tseacloud --from-file=internal_users.yml```
4. Deploy a new opensearch chart with this secret.
```
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
  internalUsersSecret: opensearch-internal-users
```
5. Deploy opensearch dashboards chart with below values.
```
config:
 opensearch_dashboards.yml:
    server.host: "0"
    opensearch.hosts: ["https://localhost:9200"]
    opensearch.ssl.verificationMode: none
    opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]
    # Use this setting if you are running opensearch-dashboards without https
    opensearch_security.cookie.secure: false
    opensearch.username: "kibanaserver"
    opensearch.password: "k$VK57-8"
    logging.verbose: true
```
Am I following the correct steps to generate password and using the secret? 

**Chart Name**
opensearch version: 1.5.4
opensearch-dashboards version: 1.1.1

**Host/Environment (please complete the following information):**
 - Helm Version: v3.7.2
 - Kubernetes Version: v1.22.1
