### ISSUE TITLE
[BUG] opensearch-dashboards helm install fails with 1.2.1

### ISSUE THREAD

**Issue by pgier** [opensearch-project/helm-charts#217]
**Describe the bug**
Not able to install opensearch-dashboards using 1.2.1 version of helm chart.  My values file works fine with 1.2.0 and earlier.

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap.data.opensearch_dashboards.yml): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"
```

**To Reproduce**
Minimal values file (based on the default values) which reproduces the issue:
```
config:
  # Default OpenSearch Dashboards configuration from docker image of Dashboards
  opensearch_dashboards.yml:
    server:
      # name: dashboards
      # host: 0.0.0.0

      # Dashboards TLS Config (Ensure the cert files are present before enabling SSL
      ssl:
        enabled: true
        key: /usr/share/opensearch-dashboards/certs/dashboards-key.pem
        certificate: /usr/share/opensearch-dashboards/certs/dashboards-crt.pem
```

**Chart Name**
opensearch-dashboards

**Host/Environment (please complete the following information):**
 - Helm Version: 3.x
 - Kubernetes Version: 1.21

**Comment by pgier** [comment]
This seems to be caused by the recent PR #214 which expects opensearch_dashboards.yml to be configured as a string, and not as yaml.  This is a breaking change, and probably should have at least a minor version increment.
The example default values file should also be updated to reflect the change in behavior.

**Comment by vliska** [comment]
Hi. Was this change even necessary? Even default config documentation states that you should use map and our config used to work fine prior 1.2.1. This is really breaking change (and caused us some headache) - shouldn't be just patch version.

`  config:
    opensearch_dashboards.yml:
      server.host: "0"
      server.basePath: /opensearch-dashboards
      server.rewriteBasePath: true
      server.name: opensearch-dashboards
      opensearch.hosts: ["http://opensearch-cluster-master:9200"]
`

**Comment by TheAlgo** [comment]
@pgier @vliska This was done I guess to be in uniformity with OpenSearch charts. A minor version increment was a miss here it seems.

**Comment by peterzhuamazon** [comment]
We have bumped the current version to 1.8.0 for now.
Sorry for confusing.
If there still any issues with you using the new way to deploy @pgier ?

Thanks.

**Comment by pgier** [comment]
@peterzhuamazon This issue is specific to the dashboard, so I think it needs an upgrade to 1.3.0?  Although, I think it's only helpful to release a 1.3.0 if you also release a 1.2.2 with the breaking change reverted.

**Comment by JunaidChaudry** [comment]
@pgier  I agree, the example values need to be updated to show the change as well... It took me an hour to figure out what changed from the last version that broke the configmap

**Comment by maleksan** [comment]
The same issue is with 1.4.0 helm chart.
To solve this you have to use config section with additional pipe, in this way:
```yaml
...
# https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml
config:
  # Default OpenSearch Dashboards configuration from docker image of Dashboards
  opensearch_dashboards.yml: |  # <---------------
    server:
      port: 5601
      name: opensearch-dashboards
      host: 0.0.0.0
      ssl:
        enabled: false
...
```
