### ISSUE TITLE
[BUG][opensearch-dashboards:1.3.0] - security-dashboards-plugin not visible in UI. 

### ISSUE THREAD

**Issue by JWebDev** [opensearch-project/helm-charts#236]
Hi, next bug.
Installed opensearch-dashboards with helm, but on UI Security button does not exists. 
security-dashboards-plugin is in list of visible plugins.
Default user: admin:admin

![image](https://user-images.githubusercontent.com/1653372/159268683-5ff34f0b-dad6-4fe6-b57a-1daefe35263d.png)

UI:
![image](https://user-images.githubusercontent.com/1653372/159268792-9cf5d204-1b66-400b-9212-eeb60664048f.png)

Helm:
`helm install opensearch-dashboards opensearch/opensearch-dashboards -n opensearch -f opensearch-dashboards-values.yaml`

**opensearch-dashboards-values.yaml**
```
opensearchHosts: "http://opensearch-cluster-master:9200"

image:
  repository: "opensearchproject/opensearch-dashboards"
  tag: "1.3.0"
```

![image](https://user-images.githubusercontent.com/1653372/159272647-92ac1ab4-9027-4c72-8a46-68190302ea2a.png)
