### ISSUE TITLE
[BUG][opensearch-dashboards] annotations causing ingress connection ECONNREFUSED

### ISSUE THREAD

**Issue by Hongbo-Miao** [opensearch-project/helm-charts#237]
**Describe the bug**

**To Reproduce**
When I deploy OpenSearch Dashboards by updating
https://github.com/opensearch-project/helm-charts/blob/bc015190aa54a0bdb11738ae10ccfbba055820a0/charts/opensearch-dashboards/values.yaml#L119-L138
to something like
```
ingress:
  enabled: false
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: opensearch-dashboards.example.com
      paths:
        - path: /
          backend:
            serviceName: opensearch-dashboards
            servicePort: 5601
  tls: []
```
the deployment succeed, however ingress still not working.

**Expected behavior**
Ingress should work.

**Chart Name**
opensearch-dashboards

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/3375461/159377065-4cea9841-34f2-42e2-be20-baf71a7f9d01.png">

**Host/Environment (please complete the following information):**
 - Helm Version: 3.8.0
 - Kubernetes Version: Server Version v1.19.9

**Additional context**
I found that

```yml
  annotations:
    {}
```

caused the issue, if I update to 

```yml
  annotations: {}
```

Ingress will work.
