### ISSUE TITLE
[BUG][opensearch] opensearch helm chart 1.10.1 does not apply cleanly as a patch

### ISSUE THREAD

**Issue by sastorsl** [opensearch-project/helm-charts#255]
**Describe the bug**
`opensearch` helm chart version `1.10.1` does not apply cleanly as it changes resources which can not be applied with a patch.

Referencing issue #248 and PR #250 

**To Reproduce**
1. Deploy opensearch helm chart version `1.10.0`
2. Bump the chart to `1.10.1`
3. See errormessage

**Expected behavior**
A fix release should not break a clean patch upgrade.

**Chart Name**
opensearch

**Screenshots**
```yaml
status:
  conditions:
    - lastTransitionTime: "2022-04-28T19:39:51Z"
      message: upgrade retries exhausted
      reason: UpgradeFailed
      status: "False"
      type: Ready
    - lastTransitionTime: "2022-04-28T19:39:51Z"
      message: |-
        Helm upgrade failed: cannot patch "fsapplog-opensearch-master" with kind StatefulSet: StatefulSet.apps "fsapplog-opensearch-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden

        Last Helm logs:

        Patch Service "fsapplog-opensearch-master" in namespace fsapplog
        Patch Service "fsapplog-opensearch-master-headless" in namespace fsapplog
        Patch StatefulSet "fsapplog-opensearch-master" in namespace fsapplog
        error updating the resource "fsapplog-opensearch-master":
             cannot patch "fsapplog-opensearch-master" with kind StatefulSet: StatefulSet.apps "fsapplog-opensearch-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
        warning: Upgrade "fsapplog-opensearch" failed: cannot patch "fsapplog-opensearch-master" with kind StatefulSet: StatefulSet.apps "fsapplog-opensearch-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
      reason: UpgradeFailed
      status: "False"
      type: Released
  failures: 65
  helmChart: flux-system/fsapplog-fsapplog-opensearch
  lastAppliedRevision: 1.10.0
  lastAttemptedRevision: 1.10.1
  lastAttemptedValuesChecksum: d2afcc3cd9d95d88df5a0664a98ea0564978e444
  lastReleaseRevision: 3
  observedGeneration: 2
  upgradeFailures: 1
```

**Host/Environment (please complete the following information):**
 - Helm Version: [e.g. 3.2.x]
 - Kubernetes Version: [e.g. 1.22.x]

**Additional context**
N/A
