### ISSUE TITLE
[SAML] Error with gsuite provider

### ISSUE THREAD

**Issue by ichasco-heytrade** [opensearch-project/helm-charts#268]
I am getting errors with gsuite (I am not 100% sure if I have configured as has to be?

config.yaml:

```
_meta:
            type: "config"
            config_version: 2

          config:
            dynamic:
              http:
                anonymous_auth_enabled: false
                # xff:
                #   enabled: false
              authc:
                basic_internal_auth_domain:
                  description: "Authenticate via HTTP Basic against internal users database"
                  http_enabled: true
                  transport_enabled: true
                  order: 0
                  http_authenticator:
                    type: basic
                    challenge: false
                  authentication_backend:
                    type: intern
                saml_auth_domain:
                  order: 1
                  description: "SAML provider"
                  http_enabled: true
                  transport_enabled: true
                  http_authenticator:
                    type: saml
                    challenge: true
                    config:
                      idp:
                        metadata_file: "/usr/share/opensearch/plugins/opensearch-security/securityconfig/gsuite.xml"
                        entity_id: ENTITY_ID
                      sp:
                        entity_id: kibana-saml
                      kibana_url: https://kibana.example.com
                      subject_key: NameID
                      roles_key: Role
                  authentication_backend:
                    type: noop
        gsuite.xml: |-
          XML_FILE
```

opensearch_dashboards.yml
```
      timelion.ui.enabled: true
      server.name: dashboards
      server.host: "0"
      server.ssl.enabled: "false"
      server.xsrf.whitelist: ["/_plugins/_security/saml/acs","/_plugins/_security/saml/acs/idpinitiated","/_plugins/_security/saml/logout","/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
      opensearch.username: dashboard
      opensearch.password: PASSWORD
      opensearch.ssl.verificationMode: "none"
      opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      opensearch_security.auth.type: "saml"
```

GSUITE conf:

* Url ACS: https://kibana.example.com/_plugins/_security/saml/acs/idpinitiated

* Entity ID: kibana-saml

Opensearch Error:
```
opensearch-0 opensearch [2022-05-22T19:59:52,786][WARN ][c.a.d.a.h.s.Saml2SettingsProvider] [opensearch-0] The IdP does not provide a Single Logout Service. In order to ensure that users have to re-enter their password after logging out, OpenSearch Security will issue all SAML authentication requests with a mandatory password input (ForceAuthn=true)
opensearch-0 opensearch [2022-05-22T19:59:52,951][ERROR][c.a.d.a.h.s.HTTPSamlAuthenticator] [opensearch-0] Error creating HTTPSamlAuthenticator. SAML authentication will not work
opensearch-0 opensearch java.lang.Exception: Settings for key exchange missing. Please specify at least the option exchange_key with a shared secret.
opensearch-0 opensearch [2022-05-22T19:59:52,959][WARN ][o.o.s.s.ReflectionHelper ] [opensearch-0] Unable to enable 'com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator' due to java.lang.reflect.InvocationTargetException
opensearch-0 opensearch [2022-05-22T19:59:52,968][ERROR][o.o.s.s.DynamicConfigModelV7] [opensearch-0] Unable to initialize auth domain saml_auth_domain=AuthcDomain [http_enabled=true, transport_enabled=false, order=1, http_authenticator=HttpAuthenticator [challenge=true, type=saml, config={idp={metadata_file=/usr/share/opensearch/plugins/opensearch-security/securityconfig/gsuite.xml, entity_id=https://accounts.google.com/o/saml2?idpid=C00zheihw}, sp={entity_id=https://kibana.example.com,}, kibana_url=https://kibana.example.com, subject_key=NameID, roles_key=department}], authentication_backend=AuthcBackend [type=noop, config={}], description=SAML provider] due to OpenSearchException[java.lang.reflect.InvocationTargetException]; nested: InvocationTargetException; nested: RuntimeException[java.lang.Exception: Settings for key exchange missing. Please specify at least the option exchange_key with a shared secret.]; nested: Exception[Settings for key exchange missing. Please specify at least the option exchange_key with a shared secret.];
```

OpenSearch dashboard error:

```
opensearch-dashboards-8445dccccb-dzsx5 dashboards {"type":"response","@timestamp":"2022-05-22T20:11:55Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"kibana.example.com","pragma":"no-cache","cache-control":"no-cache","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br","accept-language":"es-ES,es;q=0.9,en;q=0.8","x-forwarded-for":"10.10.11.102","x-forwarded-proto":"https","x-envoy-internal":"true","x-request-id":"c91a3535-90e0-9a12-b5bd-9e976f8ed777","x-envoy-decorator-operation":"opensearch-dashboards.opensearch.svc.cluster.local:5601/*","res":{"statusCode":302,"responseTime":2,"contentLength":9},"message":"GET / 302 2ms - 9.0B"}
opensearch-1 opensearch [2022-05-22T20:11:55,354][WARN ][o.o.s.a.BackendRegistry  ] [opensearch-1] Authentication finally failed for null from 10.10.10.37:41430
opensearch-dashboards-8445dccccb-dzsx5 dashboards {"type":"log","@timestamp":"2022-05-22T20:11:55Z","tags":["error","plugins","securityDashboards"],"pid":1,"message":"Failed to get saml header: Authentication Exception :: {\"path\":\"/_plugins/_security/authinfo\",\"query\":{},\"statusCode\":401,\"response\":\"Authentication finally failed\"}"}
opensearch-dashboards-8445dccccb-dzsx5 dashboards {"type":"error","@timestamp":"2022-05-22T20:11:55Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:143:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:97:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:92:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:164:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"http://kibana.example.com/auth/saml/login?nextUrl=%2Fapp%2Fopensearch-dashboards","message":"Internal Server Error"}
opensearch-dashboards-8445dccccb-dzsx5 dashboards {"type":"response","@timestamp":"2022-05-22T20:11:55Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/auth/saml/login?nextUrl=%2Fapp%2Fopensearch-dashboards","method":"get","headers":{"host":"kibana.example.com","pragma":"no-cache","cache-control":"no-cache","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\"","accept-encoding":"gzip, deflate, br","accept-language":"es-ES,es;q=0.9,en;q=0.8","x-forwarded-for":"10.10.11.102","x-forwarded-proto":"https","x-envoy-internal":"true","x-request-id":"8e041047-8a15-9a9b-882f-31675d1f2aa5","x-envoy-decorator-operation":"opensearch-dashboards.opensearch.svc.cluster.local:5601/*","res":{"statusCode":500,"responseTime":23,"contentLength":9},"message":"GET /auth/saml/login?nextUrl=%2Fapp%2Fopensearch-dashboards 500 23ms - 9.0B"}
opensearch-dashboards-8445dccccb-dzsx5 dashboards {"type":"response","@timestamp":"2022-05-22T20:11:55Z","tags":[],"pid":1,"method":"get","statusCode":401,"req":{"url":"/favicon.ico","method":"get","headers":{"host":"kibana.example.com","pragma":"no-cache","cache-control":"no-cache","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36","sec-ch-ua-platform":"\"Linux\"","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","sec-fetch-site":"same-origin","sec-fetch-mode":"no-cors","sec-fetch-dest":"image","referer":"https://kibana.example.com/auth/saml/login?nextUrl=%2Fapp%2Fopensearch-dashboards","referer":"https://kibana.example.comauth/saml/login?nextUrl=%2Fapp%2Fopensearch-dashboards"},"res":{"statusCode":401,"responseTime":2,"contentLength":9},"message":"GET /favicon.ico 401 2ms - 9.0B"}
```

OpenSearch & Dashboard version: `2.0.0-rc1`

Deployed with HELM

**Comment by ichasco-heytrade** [comment]
When created the key_exchange is fixed these problems:

```
pwgen -n 32
```

But I get now a 401 error on login:

```

referer":"https://kibana.example.com/_plugins/_security/saml/acs/idpinitiated"},"res":{"statusCode":401,"responseTime":2,"contentLength":9},"message":"GET /favicon.ico 401 2ms - 9.0B"}
```

**Comment by ichasco-heytrade** [comment]
The problem was the correct URL to set in Gsuite ACS is:

```
https://kibana.example.com/_opendistro/_security/saml/acs
```

This is a mistake in the documentation

**Comment by nomopo45** [comment]
Hey i'm running into similar issue, could you tell me which version you used for opensearch and opensearch dashboard ?

**Comment by ichasco-heytrade** [comment]
My config is:
```
              saml_auth_domain:
                  order: 1
                  description: "SAML provider"
                  http_enabled: true
                  transport_enabled: false
                  http_authenticator:
                    type: saml
                    challenge: true
                    config:
                      idp:
                        metadata_file: "/usr/share/opensearch/plugins/opensearch-security/securityconfig/gsuite.xml"
                        entity_id: ${vault:/devops/data/Google/SAML/OpenSearch#ENTITY_ID}
                      sp:
                        entity_id: kibana-saml
                      kibana_url: https://logs.example.com
                      subject_key: NameID
                      roles_key: Role
                      # Generated `pwgen -n 32`
                      exchange_key: ${vault:/devops/data/OpenSearch/Secrets#Exchange_Key}
                  authentication_backend:
                    type: noop
```
Y added the exchange_key

And OpenSearch Dashboard config:

```
server.name: dashboards
      server.host: "0"
      server.ssl.enabled: "false"
      server.xsrf.allowlist: ["/_plugins/_security/saml/acs","/_plugins/_security/saml/acs/idpinitiated","/_plugins/_security/saml/logout","/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
      opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
      opensearch.username: dashboard
      opensearch.password: ${vault:/devops/data/OpenSearch/Users/Dashboard#Password}
      opensearch.ssl.verificationMode: "none"
      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: ["Developers", "Devops"]
      opensearch_security.multitenancy.tenants.enable_private: false
      opensearch_security.multitenancy.tenants.enable_global: false
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      opensearch_security.auth.type: "saml"
```
Try to add also `requestHeadersAllowlist` parameter

And If you are not able to fix with this changes, paste also the gsuite configuration.
