### ISSUE TITLE
[BUG][OpenSearch] Tenants file doesn't work

### ISSUE THREAD

**Issue by ichasco-heytrade** [opensearch-project/helm-charts#274]
**Describe the bug**
When configuring the tenants.yml file in the chart, it doesn't create it

**To Reproduce**
1. Define tenants.yml
```
tenants.yml: |-
          _meta:
            type: "tenants"
            config_version: 2

          Devops:
            reserved: false
            description: "DevOps tenant"

          Developers:
            reserved: false
            description: "Developers tenant"
```
2- apply the chart

**Expected behavior**
Create only the tenants in the file

**Chart Name**
Opensearch

**Comment by zelinh** [comment]
[Triage] @ichasco-heytrade Could you help us raise a PR to resolve this if you have time for contributing.

**Comment by prudhvigodithi** [comment]
Hey @ichasco-heytrade when you update the `securityConfig.config.data.tenants.yml` you also need to update the other existing yaml files under  `securityConfig.config.data`,  If you only want to update the `tenants.yml` and leave other files as it is better to use the secret way to create a `tenantsSecret` and update the `securityConfig.tenantsSecret` value, this will ensure all the remaining `yml` files are not modified. I have tested your example and seem to work.

#### Step 1
1) Create a secret
```
apiVersion: v1
data:
  tenants.yml: X21ldGE6CiAgdHlwZTogInRlbmFudHMiCiAgY29uZmlnX3ZlcnNpb246IDIKCkRldm9wczoKICByZXNlcnZlZDogZmFsc2UKICBkZXNjcmlwdGlvbjogIkRldk9wcyB0ZW5hbnQiCgpEZXZlbG9wZXJzOgogIHJlc2VydmVkOiBmYWxzZQogIGRlc2NyaXB0aW9uOiAiRGV2ZWxvcGVycyB0ZW5hbnQiCg==
kind: Secret
metadata:
  name: tenants-secret
  namespace: default
  ```
2) Update the `securityConfig.tenantsSecret` to point to the above secret `tenants-secret`.

![Screenshot 2023-05-01 at 3 41 02 PM](https://user-images.githubusercontent.com/28733332/235543933-46dc1fbd-73dd-43d3-aeb5-bc6aef95ea5b.png)

3) Install the helm chart and dashboard.

![Screenshot 2023-05-01 at 3 37 20 PM](https://user-images.githubusercontent.com/28733332/235543979-70c1d669-abbf-4e41-bdfc-44d4d33388ac.png)

Closing this issue, please feel free to re-open if required.
@bbarani @peterzhuamazon @TheAlgo 

Thank you
