### ISSUE TITLE
[BUG][Opensearch] Ineffective NetworkPolicy

### ISSUE THREAD

**Issue by smlx** [opensearch-project/helm-charts#287]
**Describe the bug**
The [current NetworkPolicy](https://github.com/opensearch-project/helm-charts/blob/d987311e146835d48fe9eff2b522b3afef0308e5/charts/opensearch/templates/networkpolicy.yaml) doesn't do anything because the selectors it uses do not match any pods.

**To Reproduce**
1. Install Opensearch with `.Values.networkPolicy.create=true`
2. Connect to Opensearch from outside the installed namespace.

**Expected behavior**
The network policy appears to be intended to disallow connections to opensearch from outside the namespace.

**Chart Name**
Opensearch

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
 - Helm Version: 3.9.0
 - Kubernetes Version: 1.22.0

**Additional context**
Opensearch provides a network service which is intended to be used by external clients.
For that reason, I'm not sure that there is any point to a Network Policy for this chart.

Would you accept a PR that removes the network policy entirely?

**Comment by bbarani** [comment]
@dblock @reta Can you provide some additional insights on the ask here?

**Comment by reta** [comment]
@bbarani I am not very familiar with Helm charts, but it seems like the pods should have labels [1] (and network policy enabled), which could be configured here [2]

```
networkPolicy:
  create: false
  ## Enable creation of NetworkPolicy resources. Only Ingress traffic is filtered for now.
  ## In order for a Pod to access OpenSearch, it needs to have the following label:
  ## {{ template "uname" . }}-client: "true"
  ## Example for default configuration to access HTTP port:
  ## opensearch-master-http-client: "true"
  ## Example for default configuration to access transport port:
  ## opensearch-master-transport-client: "true"

  http:
    enabled: false
```

[1]  https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L397
[2] https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L130
