### ISSUE TITLE
[BUG][opensearch-dashboards] configMap can't be rendered from map 

### ISSUE THREAD

**Issue by bkomraz1** [opensearch-project/helm-charts#288]
**Describe the bug**
Configuration for opensearch-dashboard configuration files can't be defined as map anymore, but only as string. It means that configuration for specific file can't be changed incrementally by overriding some specific value, but only by replacing of whole content of configuration file is required.

Those behaviour was introduced by pull request: https://github.com/opensearch-project/helm-charts/pull/212 and merge: https://github.com/opensearch-project/helm-charts/pull/214 as fix to bug report: https://github.com/opensearch-project/helm-charts/issues/156

**To Reproduce**
1. create value files:

 1.yaml
```
config:
  opensearch_dashboards.yml:
    opensearch.hosts: ["https://opensearch-cluster-master:9200"]
    opensearch.ssl.verificationMode: none
    opensearch.username: "kibanaserver"
    opensearch.password: "change-me"
    opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
    server.ssl.enabled: true
    server.ssl.certificate: certs/tls.crt
    server.ssl.key: certs/tls.key
    opensearch.ssl.certificateAuthorities: certs/ca.crt
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]
    opensearch_security.cookie.secure: true
```

2.yaml
```
config:
  opensearch_dashboards.yml:
    opensearch.password: "CHANGED"
```

2. Validating manifest rendered by latest version of opensearch-dashbords helm chart 
`helm template opensearch/opensearch-dashboards -f 1.yaml -f 2.yaml --validate`

3. See error for k8s
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap.data.opensearch_dashboards.yml): invalid type for io.k8s.api.core.v1.ConfigMap.data: **got "map", expected "string"**

**Expected behavior**
Validating rendering with chart version before the fix:
`helm template opensearch/opensearch-dashboards -f 1.yaml -f 2.yaml --validate --version 1.2.0`
```
...
# Source: opensearch-dashboards/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-opensearch-dashboards-config
  labels:
    helm.sh/chart: opensearch-dashboards-1.2.0
    app.kubernetes.io/name: opensearch-dashboards
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
data:
  opensearch_dashboards.yml: |
    opensearch.hosts:
    - https://opensearch-cluster-master:9200
    opensearch.password: CHANGED
    opensearch.requestHeadersWhitelist:
    - authorization
    - securitytenant
    opensearch.ssl.certificateAuthorities: certs/ca.crt
    opensearch.ssl.verificationMode: none
    opensearch.username: kibanaserver
    opensearch_security.cookie.secure: true
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred:
    - Private
    - Global
    opensearch_security.readonly_mode.roles:
    - kibana_read_only
    server.ssl.certificate: certs/tls.crt
    server.ssl.enabled: true
    server.ssl.key: certs/tls.key
...
```
Config map rendered and validated correctly.

**Chart Name**
opensearch-dashboards

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: 
 ```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"} 
```
- Kubernetes Version: 
```
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.21.12-eks-a64ea69
```

**Additional context**
