### ISSUE TITLE
[BUG][opensearch-dashboards] invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"

### ISSUE THREAD

**Issue by viceice** [opensearch-project/helm-charts#295]
**Describe the bug**
#294 broke my deployment with terraform:

```
Error: error validating "": error validating data: ValidationError(ConfigMap.data.opensearch_dashboards.yml): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"
```

**values.yaml**
```yaml
config:
  opensearch_dashboards.yml: |
    server:
      name: dashboards
      host: 0.0.0.0
      ssl:
        enabled: false
```

**To Reproduce**
1. deploy dashboards chart v1.7.0 with yaml above
2. upgrade to v1.7.1

**Expected behavior**
Patch upgrade should not break existing users

**Chart Name**
opensearch-dashboards

**Screenshots**
no screenshots

**Host/Environment (please complete the following information):**
 - Helm Version: [e.g. 3.x.x] terraform hashicorp/helm v2.6.0
 - Kubernetes Version: [e.g. 1.16.x] v1.23.9+k3s1 (k3s)

**Additional context**

**Comment by prudhvigodithi** [comment]
Hey @viceice @DandyDeveloper I have raised a [PR](https://github.com/opensearch-project/helm-charts/pull/296) that should fix this issue
Now following both should work, can you please test with my fork @viceice

```
config:
  opensearch_dashboards.yml: |
     server:
       name: dashboards
       host: 0.0.0.0
```
```
config:
  opensearch_dashboards.yml: 
     server:
       name: dashboards
       host: 0.0.0.0
```
@peterzhuamazon @bbarani @TheAlgo
