### ISSUE TITLE
[BUG][opensearch-dashboards] Ingress config does not set parameters as shown in values.yaml

### ISSUE THREAD

**Issue by JustinasKO** [opensearch-project/helm-charts#299]
**Describe the bug**
values.yaml file for opensearch-dashboards ingress config look like:
```
ingress:
  enabled: false
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          backend:
            serviceName: chart-example.local
            servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```
but in template file ingress.yaml we have:
```
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.Version -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- else -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
```
We can see that in host part (old structure < 1.19 and new) values: `serviceName` and `servicePort` uses values: {{ $fullName }} and {{ $svcPort }} - instead of what you would expect looking at values.yaml example.

These values should be configurable and taken from what user set: etc
```
          - path: {{ .path }}
            backend:
              serviceName: {{ .backend.serviceName }}
              servicePort: {{ .backend.servicePort}}
```

This unexpected behaviour prevents from more complex ingress configuration even though basic config still works.

My suggested change: https://github.com/opensearch-project/helm-charts/pull/300

**To Reproduce**

**Expected behavior**

**Chart Name**
opensearch-dashboards

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: [2.2.0]
 - Kubernetes Version: [1.22]

**Additional context**
