### ISSUE TITLE
[BUG][opensearch-dashboards] Ingress path value does not work

### ISSUE THREAD

**Issue by pauloduartepinho** [opensearch-project/helm-charts#311]
When changing the ingress path from default (root value /) to custom, we are unable to access dashboards

All configuration is the default one expect for:

```
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: custom.host.local
      paths:
        - path: /search/opensearch-dashboards/
          backend:
            serviceName: "opensearch-dashboards"
            servicePort: "5601"
  tls: []
```

When accessing https://custom.host.local/search/opensearch-dashboards/ I get 404 not found :
![image](https://user-images.githubusercontent.com/1556117/186140385-4c82b126-0b69-4763-9197-abd192cf3b38.png)

Please tell me if any more info is needed.
Thank you for any help!
