### ISSUE TITLE
[BUG][OpenSearch dashboards] Can't set named port or `use-anotation` for ingress config

### ISSUE THREAD

**Issue by JustinasKO** [opensearch-project/helm-charts#314]
**Describe the bug**
When setting value ingress.hosts[1].paths[0].backend.servicePort as named port or use-annotation (to take configuration from annotations) getting error:
`Error: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"`
Etc: Using annotations to configure redirect from examples: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/

**To Reproduce**
1. Use For Kubernetes >= 1.18 
2. set values:

```
ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/actions.redirect-to-host1 = '{"type":"redirect","redirectConfig":{"host":"host1.com","path" :"/","port" :"443","protocol":"HTTPS","statusCode":"HTTP_301"}}'
  hosts:
    - host: "host1.com"
       paths:
         - path: /
          backend:
            serviceName: "opensearch-dashboards"
            servicePort: 5601
    - host: "host2.com"
       paths:
         - path: /
          backend:
            serviceName: "redirect-to-host1"
            servicePort: "use-annotation"
  tls: []
```
3. When deploying getting error: `Error: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"`

**Expected behavior**
Redirect is created

**Chart Name**
OpenSearch Dashboards

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Chart Version: [2.3.0]
 - Kubernetes Version: [1.22]

**Additional context**
