### ISSUE TITLE
[BUG][opensearch + opensearch-dashboards]

### ISSUE THREAD

**Issue by kevinlmadison** [opensearch-project/helm-charts#343]
**Describe the bug**
So I'm trying to deploy a "mostly" vanilla deployment of these two charts but I'm getting an error in the dashboard logs.
```
{"type":"log","@timestamp":"2022-10-28T15:02:05Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: socket hang up"}
{"type":"log","@timestamp":"2022-10-28T15:02:07Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: socket hang up"}
```

As far as I can tell the logs in the opensearch cluster pods look good.

**To Reproduce**
I'm running this in RKE2 but I'm granting unrestricted access via podSecurityPolicies.

`helm install opensearch opensearch/opensearch -n admin -f values.yaml`

```
values.yaml:
rbac:
  serviceAccountName: "admin"
podSecurityPolicy:
  create: false
  name: "system-unrestricted-psp"
```

`helm install opensearch-dashboards opensearch/opensearch-dashboards -n admin -f dashboard-values.yaml`

```
dashboard-values.yaml:
serviceAccount:
  name: "admin"
extraInitContainers:
- name: increase-vm-max-map
  image: busybox
  command: ["sysctl", "-w", "vm.max_map_count=262144"]
  securityContext:
    privileged: true
```

I can provide full log output if necessary, the only other thing I see that seems odd is this log the opensearch cluster pods:

```
tee: /usr/share/opensearch/config/opensearch.yml: Permission denied
```

**Expected behavior**
I'm expecting that the dashboard can connect to the opensearch cluster automatically
**Chart Name**
opensearch and opensearch-dashboards

**Host/Environment (please complete the following information):**
```
helm version
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
 - Kubernetes Version: [v1.22.6+rke2r1]

**Additional context**
