### ISSUE TITLE
How to deploy the opensearch  EKS cluster with multi zone in same region in.

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/helm-charts#387]
Hi Team,

We want to deploy the EKS cluster with https multi zone in same region.

In helm charts what changes need to  be change in values.yaml file. 
We added the below lines in our config file.
    **node.attr.availabilityzone: ${zone}
       cluster.routing.allocation.awareness.attributes: zone
       cluster.routing.allocation.awareness.force.zone.values: ["us-east-2a","us-east-2b","us-east-2c"]**

We are not able to see zone info inside the pod.

Please let us know how to add a **zone** to environment variables.

Please let us know what changes are to do from our side.

Thanks,
Anil

**Comment by prudhvigodithi** [comment]
Hey @ganilmca if I'm not wrong you want to run the OpenSearch in multizone, please try with the following information.

1) Make sure your EKS cluster is already on HA, multi zone nodes, consider as `a` and `b`.
2) Run the `kubectl get nodes` to see the exact zone label.
3) Use the chart  `nodeAffinity` [settings](https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch) to restrict the desired nodes.
```
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: zone, operator: In, values: ["a"]}
```
4) You can even consider taints and tolerations to restrict on a specific group, but nodeAffinity works better as you dot have to add extra taints and tolerations to the node groups.

5) Having `nodeAffinity` you can now isolate your desired OpenSearch component to specific label node that is running in a specific zone.
