### ISSUE TITLE
[BUG][opensearch] Cannot specify tag `latest`

### ISSUE THREAD

**Issue by Andrei-Stepanov** [opensearch-project/helm-charts#388]
Hello,

The Helm chart contains a bug, in particular I cannot specify tag `latest` in values.

Values:

```
image:
    # override image tag, which is .Chart.AppVersion by default
    tag: "latest"
    pullPolicy: Always
```

```
Error: Failed to render chart: exit status 1: Error: template: opensearch/templates/statefulset.yaml:9:22: executing "opensearch/templates/statefulset.yaml" at <include "opensearch.majorVersion" .>: error calling include: template: opensearch/templates/_helpers.tpl:101:18: executing "opensearch.majorVersion" at <semver (coalesce .Values.image.tag .Chart.AppVersion "1")>: error calling semver: Invalid Semantic Version

Use --debug flag to render out invalid YAML
```
