### ISSUE TITLE
[Enhancement][OpenSearch]

### ISSUE THREAD

**Issue by josephteddick** [opensearch-project/helm-charts#395]
**Is your feature request related to a problem? Please describe.**
Not a problem per say, but as described in the [OpenSearch Security Documentation](https://opensearch.org/docs/2.6/security/configuration/security-admin), when there are changes to any of the permissions (roles, users, role mappings, etc.), the securityadmin script must be executed from within OpenSearch after the pods are running. Doing this by hand every time after an installation is rather tedious. Adding the ability to automate would be very helpful.

**Describe the solution you'd like**
A solution I thought of is simply just giving users the ability to add Lifecycle Hooks to [the OpenSearch container](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/statefulset.yaml#L309). This way the user can run the securityadmin script as a postStart command. Lifecycle Hooks are a [core functionality of Kubernetes](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) and aren't really specific to my use case. Due to the nature of this being opensource, I think adding this would give users a lot of flexibility for different use cases. Also as a note, you actually [use one already](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L391) but in the [graceful termination handler container](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/statefulset.yaml#L464). 

However, this is how I would configure the Lifecycle hook to satisfy my use case:
``` yaml
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "./plugins/opensearch-security/tools/securityadmin.sh -cd ./config/opensearch-security/ -cacert config/admin/admin-root-ca.pem -cert config/admin/admin-crt.pem -key config/admin/admin-key.pem -icl -nhnv --accept-red-cluster"]
```

Depending on how long it takes OpenSearch to come up, I may have to enhance the script slightly, but at the end of the day the structure of the above block of code should be part of the OpenSearch container in the StatefulSet

**Describe alternatives you've considered**
I've thought about creating a sidecar container to do this, but it is much easier to run natively in the OpenSearch container.

**Additional context**
N/A
