### ISSUE TITLE
Opensearch Cannot apply default config (this is maybe not an error!)

### ISSUE THREAD

**Issue by rakeshreddyrg09** [opensearch-project/helm-charts#398]
**Describe the bug**
Opensearch Cannot apply default config (this is maybe not an error!)
**To Reproduce**

1. downloaded the charts -- from here -->https://github.com/opensearch-project/helm-charts/tree/main/charts
2. Applied os and os-dashboard charts getting below errors
3. Opensearch master pod error
![image](https://user-images.githubusercontent.com/48629246/223113778-a09bb956-5018-48c8-9f4c-5aae8b4c3118.png)
4. [o.o.s.c.ConfigurationLoaderSecurity7] [opensearch-cluster-master-0] Exception while retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROL │
│ ESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)

 Till this i have not applied the dashboard. Once i apply the dashboard i am getting one more error as below
 
![image](https://user-images.githubusercontent.com/48629246/223114243-1bc53944-1415-4de9-a683-594516ba4612.png)

5. Dashboard error
![image](https://user-images.githubusercontent.com/48629246/223113645-37ce7194-bdd0-44ad-a53b-db2658863e49.png)

6.  here is my config file(default am using )
```yaml
                 cluster.name: opensearch-cluster
                  # Bind to all interfaces because we don't know what IP address Docker will assign to us.
                  network.host: 0.0.0.0
                  # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
                  # Implicitly done if ".singleNode" is set to "true".
                  # discovery.type: single-node
                  # Start OpenSearch Security Demo Configuration
                  # WARNING: revise all the lines below before you go into production
                  plugins:
                    security:
                      ssl:
                        transport:
                          pemcert_filepath: esnode.pem
                          pemkey_filepath: esnode-key.pem
                          pemtrustedcas_filepath: root-ca.pem
                          enforce_hostname_verification: false
                        http:
                          enabled: true
                          pemcert_filepath: esnode.pem
                          pemkey_filepath: esnode-key.pem
                          pemtrustedcas_filepath: root-ca.pem
                      allow_unsafe_democertificates: true
                      allow_default_init_securityindex: true
                      authcz:
                        admin_dn:
                          - CN=kirk,OU=client,O=client,L=test,C=de
                      audit.type: internal_opensearch
                      enable_snapshot_restore_privilege: true
                      check_snapshot_restore_write_privileges: true
                      restapi:
                        roles_enabled: ["all_access", "security_rest_api_access"]
                      system_indices:
                        enabled: true
                        indices:
                          [
                            ".opendistro-alerting-config",
                            ".opendistro-alerting-alert*",
                            ".opendistro-anomaly-results*",
                            ".opendistro-anomaly-detector*",
                            ".opendistro-anomaly-checkpoints",
                            ".opendistro-anomaly-detection-state",
                            ".opendistro-reports-*",
                            ".opendistro-notifications-*",
                            ".opendistro-notebooks",
                            ".opendistro-asynchronous-search-response*",
                          ]
                  ######## End OpenSearch Security Demo Configuration ########
```

Can any one help me out, whats going wrong here.
Thank you
