### ISSUE TITLE
[BUG][opensearch-dashboards] livenessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type

### ISSUE THREAD

**Issue by sastorsl** [opensearch-project/helm-charts#421]
**Describe the bug**
NB! To be clear, this is not really a bug, but rather an issue when **reconfiguring** the `livenessProbe` to another handler than specified in the **default** `values.yaml`
_**This issue is to enable others to see the issue, and to document how to properly be able to change the handler if required / wanted.**_

Affected:

* `livenessProbe`
* `readinessProbe`
* `startupProbe`

Configuring / attempting to override the handler for the `livenessProbe` from `tcpSocket` to `httpGet`, or another handler type than the one in the default values **will result in an error**.

Due to the way helm merges the default parameters for `livenessProbe` in `values.yaml` with the values provided by me, the user one ends up with **two** handlers.

This results in an error message.

```
  Warning  error  32s (x2 over 5m33s)  helm-controller  reconciliation failed: Helm upgrade failed: failed to create resource: Deployment.apps "opensearch-dashboards" is invalid: spec.template.spec.containers[0].livenessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type
```

**To Reproduce**

1. Configure a `httpGet` handler in the user supplied values
2. Deploy
3. See error

**Example**

```yaml
livenessProbe:
  failureThreshold: 6
  httpGet:
    path: /auth/openid/login?nextUrl=%2F&livenessProbe
    port: https  # Name of the k8s opensearch-dashboards service port name, not the scheme
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  tcpSocket: null
  timeoutSeconds: 5
```

**Expected behavior**
That the probe was reconfigured and started working.

**Chart Name**
`opensearch-dashboards`

**Screenshots**
See reproduce info above.

**Host/Environment (please complete the following information):**
 - Helm Version: 3.11.x
 - Kubernetes Version: 1.23.x

**Additional context**
N/A
