### ISSUE TITLE
[Enhancement][opensearch][opensearch-dashboards] Lifecycle Probes

### ISSUE THREAD

**Issue by hgoscenski-imanage** [opensearch-project/helm-charts#44]
**Is your feature request related to a problem? Please describe.**
I think there ought to be liveness/readiness/startup probes for the opensearch statefulset and the opensearch-dashboards deployment.

Currently the pods are immediately marked ready on startup, leading to more than one of the nodes being unavailable which can lead to instability especially with lots of data.

**Describe the solution you'd like**
I am happy to implement something in a PR to resolve this, if that is something the project would want and my general ideas below sound good.

Opensearch:
Readiness: query health endpoint, which may require whitelisting or auth, could potentially look for green cluster status
Liveness: can check for tcp connection to 9200 or 9300
Startup: can check for health endpoint regardless of status?

Opensearch-dashboards:
Readiness: Health is at least yellow in /api/status
Liveness: 5601 is open to tcp
Startup: same as readiness

**Describe alternatives you've considered**
NA

**Additional context**
I am happy to implement if the ideas sound good.

**Comment by peterzhuamazon** [comment]
Transfer to Helm-Charts repo for new PR #43

**Comment by sastorsl** [comment]
Regarding `opensearch` there is an example of `lifecycle.postStart`, but none for `opensearch-dashboards`.

For `opensearch-dashboards` I've implemented this, and it works.
Dashboards takes over 60 seconds to start, depending on your HW of course, but leave plenty of leeway in the TIMEOUT setting.

```yaml
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "echo $(date +%F-%T) This is the end."]
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          # Wait for the application to start
          # NB! Update http / https if you have / don't have https.
          # Set a contextroot if you add one in opensearch_dashboards.yml / server.basePath
          URL=http://127.0.0.1:5601/<context-root-if-defined>
          TIMEOUT=180
          #
          # Wait until the server responds
          #
          timeout ${TIMEOUT} bash -c 'while ! [[ "$(curl -s -o /dev/null -w %{http_code}\\n '$URL')" =~ ^[23][0-9][0-9]$ ]]; do sleep 1; done'
```
