### ISSUE TITLE
Change opensearch default password 

### ISSUE THREAD

**Issue by ibrahimjelliti** [opensearch-project/helm-charts#451]
I deployed opensearch on eks successful but i want to customize the default password which is now `admin:admin` i cant see property for that in the values.yaml reference.

**Comment by smlx** [comment]
This default comes from the Opensearch docker image.

You can change the configuration by adding it [here](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L313-L344) in the `values.yaml`, with reference to the [Opensearch documentation](https://opensearch.org/docs/latest/security/configuration/yaml/).

**Comment by ibrahimjelliti** [comment]
Is that goes under internalUsersSecret or ita yaml file. I have my internal users in yaml there: admin user with hash and others internal users. But i still fo basic auth with admin:admin

**Comment by ibrahimjelliti** [comment]
Is that goes under internalUsersSecret as yaml file path. I have my internal users in yaml there mounted including admin user with hash and others internal users. But i still do basic auth with admin:admin
```
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
  actionGroupsSecret: "opensearch-action-groups"
  configSecret: "opensearch-config"
  internalUsersSecret: "opensearch-internal-users"
``` 

```
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-internal-users
  namespace: opensearch-cluster
type: Opaque
stringData:
  internal_users.yml: |
    ---
    # This is the internal user database
    # The hash value is a bcrypt hash and can be generated using:
    # $ plugins/opensearch-security/tools/hash.sh -p <new-password>
    
    _meta:
      type: "internalusers"
      config_version: 2
    
    # Define your internal users here
    
    ## internal users
    admin:
      hash: "$2a$05$xpV.iM.ated7lb3ZjdkEpuJQe3CIoAKbuzmtpDx.SfzcGDdxjPZKK"
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"
```
I am generating a hash for users with `mkpasswd -m bcrypt-a`
