### ISSUE TITLE
How to configure a secret in opensearch.yml config.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/helm-charts#458]
**Is your feature request related to a problem? Please describe.**
I am looking out for a way to configure opensearch.yml with a secret.

For eg:
plugins.query.datasources.masterkey: "secret"
Above master key can't be committed to github, so we need a way to integrate opensearch.yml with secrets in K8s.

**Comment by vamsi-amazon** [comment]
@prudhvigodithi  Any idea on this?

**Comment by prudhvigodithi** [comment]
Hey @vamsi-amazon, you can pre-create the secret and mount the secret using `extraVolumes:` and `extraVolumeMounts`

Example:
```
      volumeMounts:
        - name: opensearch-config
          mountPath: "/usr/share/opensearch/opensearch.yml"
          readOnly: true
  volumes:
    - name: opensearch-config
      secret:
        secretName: opensearch-config-secret
        optional: true
```
When you add as secret, make sure you comment this line https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L48 that asks for `opensearch.yml:` setting.
