### ISSUE TITLE
[BUG][helm chart of opensearch] init container for fsgroup-volume requires root

### ISSUE THREAD

**Issue by patrickdung** [opensearch-project/helm-charts#480]
**Describe the bug**

The helm chart requires root, after the helm chart is deployed:
```
      initContainers:
      - args:
        - chown -R 1000:1000 /usr/share/opensearch/data
        command:
        - sh
        - -c
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: fsgroup-volume
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-cluster-master
```
runAsUser: 0 is in securityContext.
This cause problem with some kubernetes environment which does not allow to run as root.
Like OpenShift platform. On openshift, the workaronud could be:
```oc adm policy add-scc-to-user privileged -z default```
But it requires cluster admin level privilege and may not be possible to run it as tenants.

**To Reproduce**
Deploy the default helm chart.

**Expected behavior**
Provide a method for users that cannot run the initcontainer as root (user 0).

**Chart Name**
Specify the Chart which is affected?
opensearch-2.15.0

**Screenshots**

Similar to ```level=error msg="container_linux.go:367: starting container process caused: exec: \"./opensearch-docker-entrypoint.sh\": stat ./opensearch-docker-entrypoint.sh: permission denied"```
https://github.com/opensearch-project/opensearch-devops/issues/97

**Host/Environment (please complete the following information):**
 - Helm Version: v3.13.0
 - Kubernetes Version: k3s 1.27.6

**Additional context**

**Comment by felix185** [comment]
is there a workaround for k8s, too? 
On the cluster I am working with there are policies that containers are not allowed to run with root users. Another policy is existing which forbids containers to be run as privileged.

**Comment by patrickdung** [comment]
On a newer version of the helm chart (e.g. 2.21)

The default value should be like

```
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
```

I think this should make the Opensearch helm chart to be able to run as non-root by default.
I had already installed it on a K3S, it should run as non-root.

For Openshift, I think the users need to update the UID to the values that their namespace should use.

**Comment by AntonEliatra** [comment]
Using chart version: 2.31.0 with above settings still produces initContainers that run as root, 
helm template output below:

```
- name: fsgroup-volume
        image: "busybox:latest"
        imagePullPolicy: "IfNotPresent"
        command: ['sh', '-c']
        args:
          - 'chown -R 1000:1000 /usr/share/opensearch/data'
        securityContext:
          runAsUser: 0
        resources:
          {}
        volumeMounts:
          - name: "opensearch-cluster-master"
            mountPath: /usr/share/opensearch/data
      - name: configfile
        image: "opensearchproject/opensearch:2.19.0"
        imagePullPolicy: "IfNotPresent"
        command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash
          cp -r /tmp/configfolder/*  /tmp/config/
        resources:
          {}
        volumeMounts:
          - mountPath: /tmp/config/
            name: config-emptydir
          - name: config
            mountPath: /tmp/configfolder/opensearch.yml
            subPath: opensearch.yml
```

**Comment by HLiu-amazon** [comment]
Related to https://github.com/opensearch-project/helm-charts/issues/384#issuecomment-2845792789

**Comment by patrickdung** [comment]
I had disabled the fsgroup-volume settings for the initContainer.
So, I do not see the part for fsgroup-volume in the initContainer.
As far as I know for updating permission in init container, it may require root (user 0) to perform it.

```
 initResources: {}
 #  limits:
@@ -197,7 +224,8 @@
 persistence:
   enabled: true
   # Set to false to disable the `fsgroup-volume` initContainer that will update permissions on the persistent disk.
-  enableInitChown: true
+  # enableInitChown: true
+  enableInitChown: false
   # override image, which is busybox by default
   # image: busybox
   # override image tag, which is latest by default
@@ -215,20 +243,65 @@
   #   GKE, AWS & OpenStack)
   #
   # storageClass: "-"
+  storageClass: "local-path"
   accessModes:
     - ReadWriteOnce
-  size: 8Gi
+  # size: 8Gi
+  size: 220Gi
   annotations: {}
```

**Comment by carlsonp** [comment]
Disabling the init container as described above fixed it for me as well as slightly tweaking the permissions within the image.

Part of values.yaml override:
```
podSecurityContext:
  fsGroup: null
  runAsUser: null
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  runAsUser: null

sysctl:
  enabled: false

persistence:
  enabled: true
  # https://github.com/opensearch-project/helm-charts/issues/480#issuecomment-2847059685
  # Set to false to disable the `fsgroup-volume` initContainer that will update permissions on the persistent disk.
  enableInitChown: false
```

The tweaked image:
```
FROM opensearchproject/opensearch:3.6.0

USER root
# Change ownership and permissions
# this is required for deployment to OpenShift because of UID/GID mappings
# and we cannot run as root
RUN chown -R :root /usr/share/opensearch && \
    chmod -R g+w /usr/share/opensearch && \
    chmod g+rwx /usr/share/opensearch
USER opensearch
```

I took similar steps for the Open Search Dashboard.
