### ISSUE TITLE
[Enhancement][OpenSearch] How do I connect two or more PVCs when I deploy OpenSearch with Helm Charts?

### ISSUE THREAD

**Issue by seung7642** [opensearch-project/helm-charts#507]
How do I connect two or more PVCs when I deploy OpenSearch with Helm Charts?
PVC can be attached by modifying the "persistence" property in the _values.yaml_ setting file, but more than one does not seem possible.

```
persistence:
  enabled: true
  enableInitChown: true
  storageClass: "my-storage-class"
```

Thank you in advance for sharing your knowledge.
