### ISSUE TITLE
[BUG][OpenSearch] Unable to use existing PVC in Opensearch value

### ISSUE THREAD

**Issue by Uritassa** [opensearch-project/helm-charts#517]
Hi, I’m encountering an issue where I cannot attach a volume to the OpenSearch master pod. Instead, it attempts to create a new PVC.
I have a Helm chart with the following values for OpenSearch:

```
opensearch:
  install: true
  persistence:
    enabled: true
    existingClaim: opensearch-data

``` 

I also tried these values

```
opensearch:
  install: true
  persistence:
    enabled: true
    volumeClaimTemplates:
      - metadata:
          name: opensearch-data
``` 
Additional Information:

    Helm chart version: latest
    Kubernetes version: 26+
    Opensearch version: latest

Environment:

    Kubernetes cluster type: EKS
    Operating system: AL2023
    Helm version: 3.0+
