### ISSUE TITLE
multiple config files

### ISSUE THREAD

**Issue by scandinavianpengue** [opensearch-project/helm-charts#541]
Hello,

i'm trying to override some keys in the opensearch_dashboards.yml (located in /usr/share/opensearch-dashboards/config/)
I have seen i can create the config: key in the custom values file, but in there i can create only the whole file, either as multistring with the |, either as configmap.

I've also seen that opensearch-dashboard can be executed giving multiple config files on the command line (ops-d -c file1 -c file2 ... )
It is not clear how can i add just some keys and not having to include the whole file in the config: key.
Specifically i'm trying to change:

```
opensearchDashboards.branding:
  logo:
    defaultUrl: URL
    darkModeUrl: URL
  mark:
    defaultUrl: URL
    darkModeUrl: URL
  loadingLogo:
    defaultUrl: URL
    darkModeUrl:URL
  faviconUrl: URL
  applicationTitle: TITLE
```

Could you please point in the right direction?
Thank you
