### ISSUE TITLE
[BUG][opensearch-2.20.0] ADMIN_INITIAL_PASSWORD not used?

### ISSUE THREAD

**Issue by cdprete** [opensearch-project/helm-charts#548]
Hello.
I'm using the opensearch-2.20-0 Helm chart and, as per documentation, I've set
```yaml
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "some-password"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
```
So far, so good. :)

Now, trying to curl the health of the cluster from within the Pod itself with
```bash
curl -ku admin:some-password http://localhost:9200/_cluster/health
```
leads to a 401 response, while a curl like
```bash
curl -ku admin:admin http://localhost:9200/_cluster/health
```
works without any issue.

So, I was wondering if the admin initial password is really used and, if it's, how?

**Comment by peterzhuamazon** [comment]
Hi @cdprete if this is not a fresh install and you have previously setup a password already, then the old password will be used still.

**Comment by peterzhuamazon** [comment]
Also if the app version (not helm chart ver) is < 2.12.0 then this change is not taking effect.

Thanks.

**Comment by cdprete** [comment]
Hi.
These are the information about the chart:
```yaml
apiVersion: v2
appVersion: 2.14.0
description: A Helm chart for OpenSearch
home: https://opensearch.org
maintainers:
- name: DandyDeveloper
- name: bbarani
- name: gaiksaya
- name: peterzhuamazon
- name: prudhvigodithi
- name: TheAlgo
name: opensearch
sources:
- https://github.com/opensearch-project/opensearch
- https://github.com/opensearch-project/helm-charts
type: application
version: 2.20.0
```

Moreover, it's a fresh installation, in fact I had to set it up that env variable since the beginning.
