### ISSUE TITLE
[BUG][opensearch-dashboards] opensearch_security not working?

### ISSUE THREAD

**Issue by rdvansloten** [opensearch-project/helm-charts#561]
**Describe the bug**
When Attempting to leverage the security plugin, Dashboards pods crash and tell me:

```
{"type":"log","@timestamp":"2024-07-16T09:32:18Z","tags":["fatal","root"],"pid":1,"message":"InvalidConfigurationError: Unknown configuration key(s): \"​opensearch_security.auth.type\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/usr/share/opensearch-dashboards/src/core/server/legacy/config/ensure_valid_configuration.js:50:11)\n    at Server.setup (/usr/share/opensearch-dashboards/src/core/server/server.js:156:5)\n    at Root.setup (/usr/share/opensearch-dashboards/src/core/server/root/index.js:60:14)\n    at bootstrap (/usr/share/opensearch-dashboards/src/core/server/bootstrap.js:113:5)\n    at Command.<anonymous> (/usr/share/opensearch-dashboards/src/cli/serve/serve.js:192:5) {\n  code: 'InvalidConfig',\n  processExitCode: 64,\n  cause: undefined\n}"}
```

**To Reproduce**
1. Go to your values.yaml
2. Add this in:
```
    opensearch.hosts: [https://localhost:9200]
    opensearch.ssl.verificationMode: none
    opensearch.username: kibanaserver
    opensearch.password: kibanaserver
    opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opensearch_security.readonly_mode.roles: [kibana_read_only]

    # Use this setting if you are running opensearch-dashboards without https
    opensearch_security.cookie.secure: false
    server.host: '0.0.0.0'
    ​opensearch_security.auth.type: ["basicauth","saml"]
    opensearch_security.auth.multiple_auth_enabled: true
```

**Expected behavior**
I expected ot be able to config SAML.

**Chart Name**
opensearch-dashboards, latest

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: 3.15.2
 - Kubernetes Version: 1.28.9

**Additional context**
Opensearch Helm values.yaml config:
```
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/config/opensearch-security"
  config:
    dynamic:
      authc:
        saml_auth_domain:
          http_enabled: true
          transport_enabled: false
          order: 1
          http_authenticator:
            type: saml
            challenge: true
            config:
              idp:
                metadata_url: https://login.microsoftonline.com/REDACTED
    #SAML's metadata url, provided by your IdP
                Entity_id: https://sts.windows.net/REDACTED/
    #SAML's IdP entity ID, provided by your IdP
              sp:
                entity_id: opensearch-ad-sso
              kibana_url: REDACTED/_dashboards
              roles_key: Roles
              exchange_key: "REDACTED"
          authentication_backend:
            type: noop
        basic_internal_auth_domain:
          description: "Authenticate via HTTP Basic against internal users database"
          http_enabled: true
          transport_enabled: true
          order: 0
          http_authenticator:
            type: basic
            challenge: false
          authentication_backend:
            type: intern
```
