### ISSUE TITLE
[BUG][opensearch] extrainitcontainers not rendered correctly

### ISSUE THREAD

**Issue by sandervandegeijn** [opensearch-project/helm-charts#568]
**Describe the bug**
Extra initcontainers seem to be rendered incorrectly

**To Reproduce**

values.yaml:

```
os-master:
  ## Define master node configuration
  clusterName: &clusterName opensearch-k8s

  # Define what role this nodeGroup is part of
  nodeGroup: "master"

  # What is the role of the node
  roles:
    - master

  replicas: 3

  global:
    # Set if you want to change the default docker registry, e.g. a private one.
    dockerRegistry: *dockerRegistry
  
  extraInitContainers:
  - name: remove-java-heap-dumps
    image: x:1.32.0
    volumeMounts:
      - name: "opensearch-k8s-master"
        mountPath: /usr/share/opensearch/data
    command:
      - sh
      - -c
      - "rm -f /usr/share/opensearch/data/*.hprof"
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "64Mi"
```

Renders as:

Notice the name missing, it's starting with the command

**Expected behavior**
Render extrainitcontainers properly.

**Chart Name**
opensearch 2.21.0

**Screenshots**

**Host/Environment (please complete the following information):**
➜  opensearch git:(main) ✗ helm version
version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}

**Additional context**
N/A
