### ISSUE TITLE
[New Chart][Logstash]

### ISSUE THREAD

**Issue by TheAlgo** [opensearch-project/helm-charts#6]
**Is your feature request related to a problem? Please describe.**
A chart for Logstash will be helpful in deploying OpenSearch stacks to Kubernetes

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
This will help cater many use-cases for log ingestion, analytics etc.

**Comment by michaelharrer** [comment]
Are there any updates regarding this chart?
@sastorsl is there some documentation about the bitnami solution? A "curated" chart would be really, really helpful.

**Comment by rebbuh** [comment]
I would also really like to have an "official" chart which gets maintained.

**Comment by tgeek77** [comment]
I'm not the most experienced at writing helm charts, but looking at the docker images from opensearch.org and the one used by bitnami, they are quite similar and perhaps it won't be a huge amount of work to replace the opensearch image with the bitnami image. The best part is that the bitname helm chart is released with an Apache license so there shouldn't be any licensing issues.
Opensearch Image: docker.io/opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
Btinami Image: docker.io/bitnami/logstash:8.6.2-debian-11-r3

**Comment by ahmadabulaban** [comment]
Any updates on this issue ? 

Really appreciated if we can have an official chart for opensearch logstash

Now the options is to use

https://artifacthub.io/packages/helm/bitnami/logstash (last version 5.3.2 - 2 May, 2023)
vs
https://artifacthub.io/packages/helm/elastic/logstash (last version 8.5.1 - 16 Nov, 2022)

The bitnami one released with an Apache license, but the file structure of docker image is different. I see that the official logstash chart is the similar one from docker image structure point of view

**Comment by sastorsl** [comment]
The elastic chart works, if you mount a couple of directories.
However, elastic is sunsetting their helm charts, akà handing them over to the community.

```yaml
    extraVolumes: |
      - name: logstash-patterns
        configMap:
          name: custom-logstash-patterns
      - name: logstash-conf-d
        configMap:
          name: custom-logstash-conf-d
    extraVolumeMounts: |
      - mountPath: /usr/share/logstash/patterns  # GROK patterns
        name: logstash-patterns
        readOnly: true
      - mountPath: /usr/share/logstash/pipeline/logstash.conf  # Input, filter and output config
        name: logstash-conf-d
        subPath: logstash.conf
        readOnly: true
```

Guess I'll check out the bitnami charts.
