### ISSUE TITLE
[Enhancement][data-prepper] Support configurable image.registry

### ISSUE THREAD

**Issue by janhoy** [opensearch-project/helm-charts#630]
**Is your feature request related to a problem? Please describe.**
Many organizations do not pull images from docker hub, but always thorugh a private registry (cache). Now, we have to modify `image.repository` to something like `my.registry/opensearchproject/data-prepper`.

**Describe the solution you'd like**
Follow the pattern from the `opensearch` char and offer a `dockerRegistry`value:

```yaml
global:
  # Set if you want to change the default docker registry, e.g. a private one.
  dockerRegistry: ""
```

**Describe alternatives you've considered**
None

**Additional context**
None
