### ISSUE TITLE
[Enhancement][data-prepper] Support configurable initContainers

### ISSUE THREAD

**Issue by janhoy** [opensearch-project/helm-charts#643]
**Is your feature request related to a problem? Please describe.**

Not possible to configure init containers for the data-prepper pod.

**Describe the solution you'd like**

User should be able to add their own custom init container for data-prepper to their `values.yaml` file, through a simple

```yaml
initContainers:
  - name: foo
    image: busybox
    command: ls
```

**Describe alternatives you've considered**

Fork the chart

**Additional context**

N/A
