### ISSUE TITLE
[BUG][OpenSearch] Incorrect indentation for `extraVolumeMounts` in `statefulset.yaml`

### ISSUE THREAD

**Issue by sastorsl** [opensearch-project/helm-charts#65]
**Describe the bug**
The Stateful Set template specifies an incorrect indentation of 10 for extraVolumeMounts. The correct value should be 8.

**To Reproduce**

Specify values for the `extraVolumeMounts` stanza in the `values.yaml` file for the OpenSearch chart. For example,

<details>
  <summary>extraVolumeMounts example</summary>

```yaml
extraVolumeMounts:
- name: extras
  mountPath: /usr/share/extras
  readOnly: true
```  
</details>

**Expected behavior**
The chart should install.

**Chart Name**
opensearch

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
Helm Version: 3.7.0
Kubernetes Version: 1.21.5

**Additional context**
Will update PR #63
