### ISSUE TITLE
[BUG][opensearch] Cannot specify additional ServiceMonitor service selector labels

### ISSUE THREAD

**Issue by erhhung** [opensearch-project/helm-charts#673]
**Describe the bug**

The `ServiceMonitor` template of the `opensearch` chart currently renders with service selector like the following:

```yaml
selector:
  matchLabels:
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/name: opensearch
```

It uses this template code that brings in the same set of **standard labels** assigned to **both the regular Service and headless Service**:

```yaml
selector:
  matchLabels:
    {{- include "opensearch.selectorLabels" . | nindent 6 }}
```

This results in twice as many Prometheus scrape targets than is necessary because both types of services are matched by the selector.

**Expected behavior**

Since the chart already provides the ability to add independent custom labels for both the regular and headless services, it would be easy to add an extra label to either service that the ServiceMonitor selector can then also require if the template allowed adding extra labels.
